make -B -feditcase
tdstrp32 -s editcase.dll editcase
@copy editcase.dll D:\Lang\BC5\FAR\Plugins\Editor\editcase>nul
@copy *.lng D:\Lang\BC5\FAR\Plugins\Editor\editcase>nul
@copy *.hlf D:\Lang\BC5\FAR\Plugins\Editor\editcase>nul
@copy editcase.dll c:\FAR\Plugins\Editor\editcase>nul
@copy *.lng c:\FAR\Plugins\Editor\editcase>nul
@copy *.hlf c:\FAR\Plugins\Editor\editcase>nul
@copy *.cpp D:\Lang\BC5\FAR>nul
