#include <farversion.hpp>

#define PLUGIN_BUILD 26
#define PLUGIN_DESC L"Text case conversion for Far Manager"
#define PLUGIN_NAME L"EditCase"
#define PLUGIN_FILENAME L"EditCase.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
