#include "farversion.hpp"

#define PLUGIN_BUILD 5
#define PLUGIN_DESC L"Hello World Plugin for FAR Manager"
#define PLUGIN_NAME L"HelloWorld"
#define PLUGIN_FILENAME L"HelloWorld.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,PLUGIN_BUILD)
