.Language=Belarussian,Belarussian (Беларуская)

lang = be
plugin.name = <(NAME)>

# Extract dialog
extract.dlg.title = РАспакоўка архіву
extract.dlg.dst_dir = &Выняць файлы ў:
extract.dlg.ignore_errors = &Прапускаць файлы з памылкамі
extract.dlg.oa = Калі файл існуе:
extract.dlg.oa_ask = &Спытаць
extract.dlg.oa_overwrite = П&еразапісаць
extract.dlg.oa_skip = П&рапусціць
extract.dlg.oa_rename = Пера&назваць
extract.dlg.oa_append = Да&даць
extract.dlg.move_files = &Выдаліць файлы з архіву пасля распакоўкі
extract.dlg.password = П&ароль:
extract.dlg.separate_dir = Распакаваць архіў у ас&обны каталог
extract.dlg.delete_archive = Вы&даліць архіў пасля распакоўкі
extract.dlg.open_dir = Пера&йсці ў мэтавы каталог пасля распакоўкі
extract.dlg.save_params = За&хаваць налады
extract.dlg.params_saved = Налады захаваны

# Update dialog
update.dlg.title = Абнаўленне архіву
update.dlg.title.create = Стварэнне архіву
update.dlg.profile = &Профіль:
update.dlg.save_profile = Захаваць
update.dlg.delete_profile = Выдаліць
update.dlg.arc_path = &Шлях:
update.dlg.arc_path_eval = Пак&азаць
update.dlg.append_ext = &Дадаць пашырэнне
update.dlg.arc_type = Фармат архіву:
update.dlg.arc_type.other = &Іншыя:
update.dlg.level = &Узровень сціску:
update.dlg.method = &Метад:
update.dlg.solid = Бесперапын&ны
update.dlg.advanced = Паш&ыраныя налады:
update.dlg.encrypt = Та&йнапіс файлаў
update.dlg.show_password = Адлюстраваць пароль
update.dlg.password = Паро&ль:
update.dlg.password2 = Праверка пароля:
update.dlg.encrypt_header = Тайнапіс загалоўка
update.dlg.create_sfx = &Стварыць самавымаемы архіў
update.dlg.sfx_options = Налады SFX
update.dlg.enable_volumes = Парэзаць на кавалк&і
update.dlg.volume_size = Памер кавалка:
update.dlg.move_files = Выдаліц&ь файлы пасля архівавання
update.dlg.open_shared = Архіваваць файлы, якія &адчынены для запісу
update.dlg.ignore_errors = Прапус&каць файлы з памылкамі
update.dlg.oa = Калі файл існуе:
update.dlg.oa_ask = &Спытаць
update.dlg.oa_overwrite = &Перазапісаць
update.dlg.oa_skip = П&рапусціць
update.dlg.enable_filter = Ужыць &фільтр
update.dlg.wrong_arc_type = Неабходна выбраць формат архіву
update.dlg.wrong_level = Неабходна выбраць узровень сціску
update.dlg.wrong_method = Неабходна выбраць метад сціску
update.dlg.passwords_dont_match = Уведзеныя паролі не супадаюць
update.dlg.password_is_empty = Неабходна паказаць пароль
update.dlg.wrong_volume_size = Неправільна паказаны памер кавалка
update.dlg.confirm_overwrite = Мэтавы архіў ужо існуе. Жадаеце перазапісаць яго?
update.dlg.input_profile_name = Увядзіце назву профіля
update.dlg.confirm_profile_delete = Жадаеце выдаліць бягучы профіль?
update.dlg.sfx_no_ppmd = Абраны SFX модуль не подтрымлівае сціск метадам PPMD
update.dlg.sfx_no_encrypt = Абраны SFX модуль не подтрымлівае тайнапіс дадзеных
update.dlg.save_params = Захаваць налады
update.dlg.params_saved = Налады захаваны

# Archive types
compression.archive.7z = &7z
compression.archive.zip = &zip

# Compression levels
compression.level.store = Store
compression.level.fastest = Fastest
compression.level.fast = Fast
compression.level.normal = Normal
compression.level.maximum = Maximum
compression.level.ultra = Ultra

# Compression methods
compression.method.lzma = LZMA
compression.method.lzma2 = LZMA2
compression.method.ppmd = PPMD

# Delete files
delete.dlg.confirm = Вы жадаеце выдаліць абраныя файлы?

# Create directory
create_dir.dlg.name = Увядзіце імя каталогу:

# Test archive
test.ok = Праверка архіва паспяхова завершаны
test.menu = Праверыць архіў

# Password dialog
password.title = Увод пароля
password.password = Пароль:

# Overwrite dialog
overwrite.dlg.title = Перазапіс файла
overwrite.dlg.question = Мэтавы файл ужо існуе. Замяніць?
overwrite.dlg.source = Крыніца:
overwrite.dlg.destination = Мэта:
overwrite.dlg.newer = (больш новы)
overwrite.dlg.all = &Запомніць выбар
overwrite.dlg.overwrite = За&мяніць
overwrite.dlg.skip = &Прапусціць
overwrite.dlg.rename = Пера&назваць
overwrite.dlg.append = &Дадаць
overwrite.dlg.cancel = &Адмяніць

# Error retry dialog
button.retry = &Паўтор
button.ignore = &Ігнараваць
button.ignore_all = Ігнара&ваць усе

# Log dialog
log.title = Спіс памылак
log.info = Дзеянне закончылася з памылкамі. Жадаеце праглядзець спіс?
log.close = &Зачыніць
log.show = &Адлюстраваць спіс

# Settings dialog
settings.dlg.handle_create = Апрацоўваць каманду стварэння архіва (Shift-F&1)
settings.dlg.handle_commands = Апрацоўваць іншыя архіўныя каманды (Ctrl-PgDn, Shift-F&2)
settings.dlg.own_panel_view_mode = Ужыць асабісты рэ&жым работы панэлі
settings.dlg.oem_codepage = Ко&давая старонка OEM:
settings.dlg.ansi_codepage = ANSI:
settings.dlg.save_codepage = &Хаваць
settings.dlg.use_include_masks = Маскі &уключэння:
settings.dlg.use_exclude_masks = Маскі &выключэння:
settings.dlg.pgdn_masks = Н&алады масак упрываюць на Ctrl-PgDn
settings.dlg.generate_masks = &Згенераваць маскі
settings.dlg.default_masks = З&вычайныя маскі
settings.dlg.use_enabled_formats = У&ключыць фарматы архіваў:
settings.dlg.use_disabled_formats = &Адключыць фарматы архіваў:
settings.dlg.pgdn_formats = &Налады фарматаў уплываюць на Ctrl-PgDn
settings.dlg.lib_info = Звесткі аб бібліятэцы &7z
settings.dlg.lib_not_found = Бібліятэка 7z не знойдзена
settings.dlg.lib_version = Версія:
settings.dlg.lib_formats = Фарматы
settings.dlg.lib_masks = Маскі
settings.dlg.active = Актыўна
settings.dlg.edit = Мяняць

# Attributes dialog
attr.dlg.title = Атрыбуты

# SFX options dialog
sfx_options.dlg.title = Налады SFX
sfx_options.dlg.profile = Ужыць про&філь:
sfx_options.dlg.module = &Модуль:
sfx_options.dlg.replace_icon = Замяніць &гузік
sfx_options.dlg.icon_path = &Шлях да ICO файла:
sfx_options.dlg.replace_version = Замяніць звестку аб &версіі
sfx_options.dlg.ver_info.version = В&ерсія:
sfx_options.dlg.ver_info.comments = &Каментар:
sfx_options.dlg.ver_info.company_name = На&зва кампаніі:
sfx_options.dlg.ver_info.file_description = &Апісанне файла:
sfx_options.dlg.ver_info.legal_copyright = Аўта&рскае права:
sfx_options.dlg.ver_info.product_name = Назва пра&дукта:
sfx_options.dlg.append_install_config = Налады усталява&ння
sfx_options.dlg.install_config.title = З&агаловак:
sfx_options.dlg.install_config.begin_prompt = &Пытанне:
sfx_options.dlg.install_config.progress = Па&казальнік распакоўкі:
sfx_options.dlg.install_config.run_program = В&ыканаць праграмму з архіва:
sfx_options.dlg.install_config.directory = Ката&лог з праграммай:
sfx_options.dlg.install_config.execute_file = Выканац&ь адвольны файл:
sfx_options.dlg.install_config.execute_parameters = Налады&ы выканання:
sfx_options.dlg.wrong_module = Неабходна паказаць SFX модуль
sfx_options.dlg.invalid_icon_path = ICO файл не знойдзены

# SFX module description
sfx_descr.7z = Стандартны
sfx_descr.7zcon = Стандартны кансольныа
sfx_descr.7zs = Устанаўленне (статычнае)
sfx_descr.7zs2 = Устанаўленне спрошчанае
sfx_descr.7zs2con = Устанаўленне спрошчанае кансольнае
sfx_descr.7zsd = Устанаўленне
sfx_descr.unknown = Невядомы

# Plugin menu
menu.open = &Адкрыць архіў
menu.detect = А&дкрыць (спіс фарматаў)
menu.create = &Стварыць архіў
menu.extract = &Распакаваць архіў(вы)
menu.test = &Праверыць архіў(вы)
menu.sfx_convert = Пера&ўтварыць архіў у SFX

# Progress messages
progress.open = Чытанне архіву...
progress.extract = Выманне файлаў...
progress.create_dirs = Стварэнне каталогаў...
progress.set_attr = Заданне атрыбутаў...
progress.test = Праверка архіва...
progress.update = Абнаўленне архіва...
progress.create = Стварэнне архіва...
progress.delete_files = Выдаленне файлаў...
progress.scan_dirs = Азіранне каталогаў...
progress.interrupt = Жадаеце перапыніць бягучае дзеянне?
progress.paused = Прыпынак
progress.low_priority = Фон
progress.sfx_convert = Пераўтварэнне ў SFX...

# Error messages
error.extract.unsupported_method = Непадтрымліваемы метад сціску
error.extract.data_error = Памылка ў дадзеных
error.extract.data_error.encrypted = Несапраўдны пароль альбо памылка ў дадзеных
error.extract.crc_error = Памылка пры праверцы кантрольнай сумы
error.extract.crc_error.encrypted = Несапраўдны пароль альбо памылка пры праверцы кантрольнай сумы
error.extract.unknown = Невядомая памылка распакоўкі
error.update.error = Памылка абнаўлення
error.extract.unavailable_data = Недасяжныя дадзеныя
error.extract.unexpected_end_data = Нечаканы канец дадзеных
error.extract.data_after_end = Ёсць дадзеныя пасле канца блоку карысных дадзеных
error.extract.is_not_archive = Не з'яўляецца архівам
error.extract.headers_error = Памылка ў загалоўках
error.extract.wrong_password = Несапраўдны пароль
error.update.unknown = Невядомая памылка абнаўлення
error.no_format = Фармат архіва не знойдзены
error.not_updatable = Змена архіва немагчыма
error.not_archive = Файл не распазнаны як архіў
error.sfx_convert = Архіў нельга пераўтварыць у SFX архіў
error.update.unsupported_for_singlefilearchive = Змена аднофайлавых архіваў немагчыма

# Generic buttons
button.ok = OK
button.cancel = Адмяніць

# Size and speed suffixes
suffix.size.b = Б
suffix.size.kb = КБ
suffix.size.mb = МБ
suffix.size.gb = ГБ
suffix.size.tb = ТБ
suffix.speed.b = Б/с
suffix.speed.kb = КБ/с
suffix.speed.mb = МБ/с
suffix.speed.gb = ГБ/с
suffix.speed.tb = ТБ/с

# Property names
kpid.Path = Шлях
kpid.Name = Імя
kpid.Extension = Пашырэнне
kpid.IsDir = Каталог
kpid.Size = Памер
kpid.PackSize = Сціснуты
kpid.Attrib = Атрыбуты
kpid.CTime = Створаны
kpid.ATime = Адчынены
kpid.MTime = Зменены
kpid.Solid = Бесперапынны
kpid.Commented = Каментар
kpid.Encrypted = Тайнапісны
kpid.SplitBefore = Падзелены Да
kpid.SplitAfter = Падзелены Пасля
kpid.DictionarySize = Слоўнік
kpid.CRC = CRC
kpid.Type = Тып
kpid.IsAnti = Анты
kpid.Method = Метад
kpid.HostOS = Сістэма
kpid.FileSystem = Файлавая Сістэма
kpid.User = Карыстальнік
kpid.Group = Суполка
kpid.Block = Блок
kpid.Comment = Каментар
kpid.Position = Месцазнаходжанне
kpid.Prefix = Прыстаўка
kpid.NumSubDirs = Каталогаў
kpid.NumSubFiles = Файлаў
kpid.UnpackVer = Версія
kpid.Volume = Том
kpid.IsVolume = Шматтомный
kpid.Offset = Зрух
kpid.Links = Спасылак
kpid.NumBlocks = Блокаў
kpid.NumVolumes = Тамоў
kpid.TimeType = Тып Часу
kpid.Bit64 = 64-bit
kpid.BigEndian = Big-endian
kpid.Cpu = Працэсар
kpid.PhySize = Фізічны Памер
kpid.HeadersSize = Памер Загалоўкаў
kpid.Checksum = Кантрольная Сума
kpid.Characts = Характарыстыкі
kpid.Va = Уяўны Адрас
kpid.Id = ID
kpid.ShortName = Кароткае імя
kpid.CreatorApp = Праграма
kpid.SectorSize = Памер сектару
kpid.PosixAttrib = Права
kpid.Link = Спасылак
kpid.Error = Памылка
kpid.TotalSize = Агульны памер
kpid.FreeSpace = Вольна
kpid.ClusterSize = Памер кластару
kpid.VolumeName = Метка
kpid.LocalName = Мясцовае Імя
kpid.Provider = Правайдэр
kpid.NtSecure = NT Бяспека
kpid.IsAltStream = Альтэрнатыўная Струмень
kpid.IsAux = Aux
kpid.IsDeleted = Выдалены
kpid.IsTree = Дрэва
kpid.Sha1 = SHA-1
kpid.Sha256 = SHA-256
kpid.ErrorType = Тып Памылкаі
kpid.NumErrors = Памылкаі
kpid.ErrorFlags = Памылкаі
kpid.WarningFlags = Папярэджанне
kpid.Warning = Папярэджанне
kpid.NumStreams = Струмені
kpid.NumAltStreams = Альтэрнатыўныя Струмені
kpid.AltStreamsSize = Памер Альтэрнатыўных струменяў
kpid.VirtualSize = Уяўны Памер
kpid.UnpackSize = Распакаваны Памер
kpid.TotalPhySize = Агульны Фізічны Памер
kpid.VolumeIndex = Нумар Тому
kpid.SubType = Падтып
kpid.ShortComment = Кароткі Каментар
kpid.CodePage = Кодавая Старонка
kpid.IsNotArcType = Не Архіўны Тып
kpid.PhySizeCantBeDetected = Фізічены памер невызначаемы
kpid.ZerosTailIsAllowed = Дазволеныя нулі ў канцы
kpid.TailSize = Памер Рэшткаў
kpid.EmbeddedStubSize = Памер Убудаванага Блоку
kpid.NtReparse = Спасылак
kpid.HardLink = Жорсткі Спасылак
kpid.INode = iNode
kpid.StreamId = ID Струмені
kpid.ReadOnly = Толькі для чытання
kpid.OutName = Out Name
kpid.CopyLink = Copy Link

# Property values
property.true = Так
property.false = Не
property.compression_ratio = Ступень сціску
property.total_size = Памер дадзеных
property.total_packed_size = Упакаваны памер
property.file_count = Колькасць файлаў
property.dir_count = Колькасць каталогаў
