.Language=Italian,Italian (Italiano)

lang = it
plugin.name = ► Compressore (<(NAME)>)

# Extract dialog
extract.dlg.title = Estrai Files
extract.dlg.dst_dir = Estrai Files In:
extract.dlg.ignore_errors = &Ignora Errori
extract.dlg.oa = Quando La Destinazione Esiste Gia':
extract.dlg.oa_ask = C&hiedi
extract.dlg.oa_overwrite = So&vrascrivi
extract.dlg.oa_skip = &Salta
extract.dlg.oa_rename = &Rinomina
extract.dlg.oa_append = &Accoda
extract.dlg.move_files = &Elimina Files Dall'Archivio Dopo Estrazione
extract.dlg.password = Pass&word:
extract.dlg.separate_dir = &Estrai In Cartelle Separate
extract.dlg.delete_archive = Elimina Arc&hivio Dopo Decompressione
extract.dlg.open_dir = Vai Alla &Cartella Dopo La Decompressione
extract.dlg.save_params = Sa&lva Impostazioni
extract.dlg.params_saved = Impostazioni Salvate

# Update dialog
update.dlg.title = Aggiungi All'Archivio
update.dlg.title.create = ◄ Crea Archivio ►
update.dlg.profile = &Profilo:
update.dlg.save_profile = &Salva
update.dlg.delete_profile = Elimina
update.dlg.arc_path = Percorso Arc&hivio:
update.dlg.arc_path_eval = Ve&di
update.dlg.append_ext = Acco&da Estensione
update.dlg.arc_type = Compressore:
update.dlg.arc_type.other = &Altri:
update.dlg.level = Livello Compressione:
update.dlg.method = Metodo:
update.dlg.solid = S&olido
update.dlg.advanced = Para&metri Avanzati:
update.dlg.encrypt = &Cripta Archivio
update.dlg.show_password = Mostra Password
update.dlg.password = Pass&word:
update.dlg.password2 = Ripeti:
update.dlg.encrypt_header = Cripta Intesta&zioni
update.dlg.create_sfx = Crea Archivio Auto&-Estraente
update.dlg.sfx_options = Opzioni SFX
update.dlg.enable_volumes = Dividi In Volu&mi
update.dlg.volume_size = Dimensione:
update.dlg.move_files = Rimuo&vi File Dopo Compressione
update.dlg.open_shared = File Compresso Aperto In &Scrittura
update.dlg.ignore_errors = &Ignora Errori
update.dlg.oa = Quando La Destinazione Esiste:
update.dlg.oa_ask = C&hiedi
update.dlg.oa_overwrite = So&vrascrivi
update.dlg.oa_skip = &Salta
update.dlg.enable_filter = Usa Filtro
update.dlg.wrong_arc_type = Seleziona Formato Archivio
update.dlg.wrong_level = Seleziona Livello Compressione
update.dlg.wrong_method = Seleziona Metodo Compressione
update.dlg.passwords_dont_match = Password Non Corrispondenti
update.dlg.password_is_empty = Password Vuota
update.dlg.wrong_volume_size = Dimensione Volume Non Valida
update.dlg.confirm_overwrite = File Di Destinazion Esistente. Desideri Sovrascriverlo?
update.dlg.input_profile_name = Nome Profilo
update.dlg.confirm_profile_delete = Vuoi Eliminare Il Profilo Selezionato?
update.dlg.sfx_no_ppmd = Il Modulo SFX Selezionato Non Supporta Compressione PPMD
update.dlg.sfx_no_encrypt = Il Modulo SFX Selezionato Non Supporta La Criptazione
update.dlg.save_params = Salva Impostazioni
update.dlg.params_saved = Impostazioni Salvate

# Archive types
compression.archive.7z = &7z
compression.archive.zip = &zip

# Compression levels
compression.level.store = Nessuna
compression.level.fastest = Veloce
compression.level.fast = Rapido
compression.level.normal = Normale
compression.level.maximum = Massimo
compression.level.ultra = Ultra

# Compression methods
compression.method.lzma = LZMA
compression.method.lzma2 = LZMA2
compression.method.ppmd = PPMD

# Delete files
delete.dlg.confirm = Vuoi Eliminare I Files Selezionati?

# Create directory
create_dir.dlg.name = Nome Della Cartella:

# Test archive
test.ok = Verifica Dell'Archivio Completata
test.menu = Verifica File Archivio

# Password dialog
password.title = Inserisci Password
password.password = Password:

# Overwrite dialog
overwrite.dlg.title = Sovrascrivi File
overwrite.dlg.question = File Di Destinazione Esistente! Sovrascrivo?
overwrite.dlg.source = Origine:
overwrite.dlg.destination = Destinazione:
overwrite.dlg.newer = (nuovi)
overwrite.dlg.all = &Ricorda Scelta
overwrite.dlg.overwrite = So&vrascrivi
overwrite.dlg.skip = &Salta
overwrite.dlg.rename = &Rinomina
overwrite.dlg.append = Acco&da
overwrite.dlg.cancel = &Annulla

# Error retry dialog
button.retry = &Riprova
button.ignore = &Ignora
button.ignore_all = Ignora &Tutti

# Log dialog
log.title = Salva Log Operazioni
log.info = Operazione Terminata Con Errori. Vuoi Visualizzarli?
log.close = &Chiudi
log.show = Mostra &Errori

# Settings dialog
settings.dlg.handle_create = Gestisci Creazione Archivi [Shift-F&1]
settings.dlg.handle_commands = Gestisci Comandi Archivi [Ctrl-PgGiù, Shift-F&2]
settings.dlg.own_panel_view_mode = &Modalità Pannello Personalizzato
settings.dlg.oem_codepage = &Codifica OEM:
settings.dlg.ansi_codepage = Codifica &ANSI:
settings.dlg.save_codepage = Sa&lva Codifica
settings.dlg.use_include_masks = Fi&ltro Apertura File Abbinati:
settings.dlg.use_exclude_masks = &Filtro Esclusione File Abbinati:
settings.dlg.pgdn_masks = Impostazione F&iltro Con Ctrl-PgGiù
settings.dlg.generate_masks = &Genera Filtri
settings.dlg.default_masks = Filtro &Standard:
settings.dlg.use_enabled_formats = &Abilita Formato Archivi:
settings.dlg.use_disabled_formats = &Disabilita Formato Archivi:
settings.dlg.pgdn_formats = Impostazione &Formato Con Ctrl-PgGiù
settings.dlg.lib_info = Info Libreria 7z
settings.dlg.lib_not_found = Libreria 7z Non Trovata
settings.dlg.lib_version = Versione:
settings.dlg.lib_formats = Formati
settings.dlg.lib_masks = Filtri
settings.dlg.active = Attivo
settings.dlg.edit = Modifica

# Attributes dialog
attr.dlg.title = Attributi

# SFX options dialog
sfx_options.dlg.title = Opzioni SFX
sfx_options.dlg.profile = Applica &Profilo:
sfx_options.dlg.module = Nome &Modulo:
sfx_options.dlg.replace_icon = Cambia &Icona
sfx_options.dlg.icon_path = &Percorso Icona:
sfx_options.dlg.replace_version = Cambia &Versione
sfx_options.dlg.ver_info.version = V&ersione:
sfx_options.dlg.ver_info.comments = &Commenti:
sfx_options.dlg.ver_info.company_name = Nome &Azienda:
sfx_options.dlg.ver_info.file_description = &Descrizione File:
sfx_options.dlg.ver_info.legal_copyright = Cop&yright Legali:
sfx_options.dlg.ver_info.product_name = &Nome Prodotto:
sfx_options.dlg.append_install_config = Configurazione In&stallatore
sfx_options.dlg.install_config.title = &Titolo:
sfx_options.dlg.install_config.begin_prompt = Promp&t Iniziale:
sfx_options.dlg.install_config.progress = Barra Prog&ressione:
sfx_options.dlg.install_config.run_program = &Esegui Programma:
sfx_options.dlg.install_config.directory = Cartel&la:
sfx_options.dlg.install_config.execute_file = Ese&gui File:
sfx_options.dlg.install_config.execute_parameters = Parametri Esec&uzione:
sfx_options.dlg.wrong_module = Seleziona Modulo SFX
sfx_options.dlg.invalid_icon_path = Percorso Icona Invalido

# SFX module description
sfx_descr.7z = GUI Standard
sfx_descr.7zcon = Console Standard
sfx_descr.7zs = GUI Installatore (statico)
sfx_descr.7zs2 = Piccola GUI Installatore
sfx_descr.7zs2con = Piccola Console Installatore
sfx_descr.7zsd = GUI Installatore
sfx_descr.unknown = Ignoto

# Plugin menu
menu.open = &Apri Archivio
menu.detect = Apri (menu &formato)
menu.create = &Crea Archivio
menu.extract = &Estrai Archivio
menu.test = &Testa Archivio
menu.sfx_convert = C&onverti In SFX

# Progress messages
progress.open = Lettura Archivio...
progress.extract = Decomprimo Files...
progress.create_dirs = Creazione Cartelle...
progress.set_attr = Imposto Attributi...
progress.test = Controllo Archivio...
progress.update = Aggiornamento Archivio...
progress.create = Creazione Archivio...
progress.delete_files = Eliminazione Files...
progress.scan_dirs = Scansione Cartelle...
progress.interrupt = Vuoi Interrompere L'Operazione Corrente?
progress.paused = Fermato
progress.low_priority = Basso
progress.sfx_convert = Conversione In SFX...

# Error messages
error.extract.unsupported_method = Metodo Di Compressione Non Supportato
error.extract.data_error = Errore Nei Dati
error.extract.data_error.encrypted = Password Errata O Errore Nei Dati
error.extract.crc_error = Controllo CRC Fallito
error.extract.crc_error.encrypted = Password Errata O CRC Fallito
error.extract.unavailable_data = Unavailable data
error.extract.unexpected_end_data = Unexpected end of data
error.extract.data_after_end = There are some data after the end of the payload data
error.extract.is_not_archive = Is not archive
error.extract.headers_error = Headers Error
error.extract.wrong_password = Wrong password
error.extract.unknown = Errore Sconosciuto Di Decompressione
error.update.error = Errore Di Aggiornamento
error.update.unknown = Errore Di Aggiornamento Sconosciuto
error.no_format = Formato Archivio Non Trovato
error.not_updatable = Modifica Archivio Non Supportata
error.not_archive = File Non Riconosciuto Come Archivio
error.sfx_convert = Impossibile Convertire In Autoestraente
error.update.unsupported_for_singlefilearchive = Can't change single file archive format

# Generic buttons
button.ok = &Ok
button.cancel = &Annulla

# Size and speed suffixes
suffix.size.b = B
suffix.size.kb = KB
suffix.size.mb = MB
suffix.size.gb = GB
suffix.size.tb = TB
suffix.speed.b = B/s
suffix.speed.kb = KB/s
suffix.speed.mb = MB/s
suffix.speed.gb = GB/s
suffix.speed.tb = TB/s

# Property names
kpid.Path = Percorso
kpid.Name = Nome
kpid.Extension = Estensione
kpid.IsDir = E' Cartella
kpid.Size = Dimensione
kpid.PackSize = Dim. Compressa
kpid.Attrib = Attributi
kpid.CTime = Creato
kpid.ATime = Consultato
kpid.MTime = Modificato
kpid.Solid = Solido
kpid.Commented = Commentato
kpid.Encrypted = Criptato
kpid.SplitBefore = Dividi Prima
kpid.SplitAfter = Dividi Dopo
kpid.DictionarySize = Dizionario
kpid.CRC = CRC
kpid.Type = Tipo
kpid.IsAnti = Anti
kpid.Method = Metodo
kpid.HostOS = Sistema Operativo
kpid.FileSystem = File System
kpid.User = Utente
kpid.Group = Guppo
kpid.Block = Blocco
kpid.Comment = Commento
kpid.Position = Posizione
kpid.Prefix = Percorso Prefisso
kpid.NumSubDirs = Cartelle
kpid.NumSubFiles = Files
kpid.UnpackVer = Versione
kpid.Volume = Volume
kpid.IsVolume = Multi-Volume
kpid.Offset = Deviazione
kpid.Links = Collegamenti
kpid.NumBlocks = Blocchi
kpid.NumVolumes = Volumi
kpid.TimeType = Tipo Orario
kpid.Bit64 = 64-bit
kpid.BigEndian = Big-endian
kpid.Cpu = CPU
kpid.PhySize = Dim. Reale
kpid.HeadersSize = Dimensione Intestazione
kpid.Checksum = Checksum
kpid.Characts = Caratteristiche
kpid.Va = Indirizzo Virtuale
kpid.Id = ID
kpid.ShortName = Nome Breve
kpid.CreatorApp = Compressore
kpid.SectorSize = Dim. Settore
kpid.PosixAttrib = Modo
kpid.Link = Collegamento
kpid.Error = Error
kpid.TotalSize = Dim. Totale
kpid.FreeSpace = Spazio Libero
kpid.ClusterSize = Dimensione Cluster
kpid.VolumeName = Etichetta
kpid.LocalName = Nome Locale
kpid.Provider = Provider
kpid.NtSecure = NT Security
kpid.IsAltStream = Alternate Stream
kpid.IsAux = Aux
kpid.IsDeleted = Deleted
kpid.IsTree = Is Tree
kpid.Sha1 = SHA-1
kpid.Sha256 = SHA-256
kpid.ErrorType = Error Type
kpid.NumErrors = Errors
kpid.ErrorFlags = Errors
kpid.WarningFlags = Warnings
kpid.Warning = Warning
kpid.NumStreams = Streams
kpid.NumAltStreams = Alternate Streams
kpid.AltStreamsSize = Alternate Streams Size
kpid.VirtualSize = Virtual Size
kpid.UnpackSize = Unpack Size
kpid.TotalPhySize = Total Physical Size
kpid.VolumeIndex = Volume Index
kpid.SubType = SubType
kpid.ShortComment = Short Comment
kpid.CodePage = Code Page
kpid.IsNotArcType = Is not archive type
kpid.PhySizeCantBeDetected = Physical Size can't be detected
kpid.ZerosTailIsAllowed = Zeros Tail Is Allowed
kpid.TailSize = Tail Size
kpid.EmbeddedStubSize = Embedded Stub Size
kpid.NtReparse = Link
kpid.HardLink = Hard Link
kpid.INode = iNode
kpid.StreamId = Stream ID
kpid.ReadOnly = Read-only
kpid.OutName = Out Name
kpid.CopyLink = Copy Link

# Property values
property.true = Si
property.false = No
property.compression_ratio = Percentuale Compressione
property.total_size = Dim. Dati
property.total_packed_size = Dim. Compressa
property.file_count = Conteggio File
property.dir_count = Conteggio Cartelle
