.Language=Polish,Polish (Polski)

lang = pl
plugin.name = <(NAME)>

# Extract dialog
extract.dlg.title = Rozpakuj pliki
extract.dlg.dst_dir = &Rozpakuj pliki do:
extract.dlg.ignore_errors = &Ignoruj błędy
extract.dlg.oa = Jeżeli plik docelowy istnieje:
extract.dlg.oa_ask = Za&pytaj
extract.dlg.oa_overwrite = Z&astąp
extract.dlg.oa_skip = &Omiń
extract.dlg.oa_rename = &Zmień nazwę
extract.dlg.oa_append = &Dołącz
extract.dlg.move_files = &Usuń pliki z archiwum po rozpakowaniu
extract.dlg.password = &Hasło:
extract.dlg.separate_dir = Rozpakuj archiwa do osobnych &folderów
extract.dlg.delete_archive = U&suń archiwum po rozpakowaniu
extract.dlg.open_dir = Przejdź do folderu docelo&wego po rozpakowaniu
extract.dlg.save_params = Zapisz ustawienia
extract.dlg.params_saved = Ustawienia zapisane

# Update dialog
update.dlg.title = Dodaj pliki do archiwum
update.dlg.title.create = Utwórz archiwum
update.dlg.profile = &Profil:
update.dlg.save_profile = Zapisz
update.dlg.delete_profile = Usuń
update.dlg.arc_path = Ścieżka &archiwum:
update.dlg.arc_path_eval = Pok&aż
update.dlg.append_ext = &Dołącz rozsz.
update.dlg.arc_type = Wybierz archiwizator:
update.dlg.arc_type.other = &Inny:
update.dlg.level = Poziom &kompresji:
update.dlg.method = &Metoda:
update.dlg.solid = S&olidne
update.dlg.advanced = Zaaw. param&etry:
update.dlg.encrypt = Za&szyfruj archiwum
update.dlg.show_password = Pokaż hasło
update.dlg.password = &Hasło:
update.dlg.password2 = Powtórz:
update.dlg.encrypt_header = Zaszyfruj nagłówek
update.dlg.create_sfx = Utwórz archiwum SF&X
update.dlg.sfx_options = Opcje SFX
update.dlg.enable_volumes = Podziel na &wolumeny
update.dlg.volume_size = Wielk. wolumenu:
update.dlg.move_files = &Usuń pliki po spakowaniu
update.dlg.open_shared = Pakuj pliki otwarte do &zapisu
update.dlg.ignore_errors = Ignoruj &błędy
update.dlg.oa = Gdy plik docelowy istnieje:
update.dlg.oa_ask = Za&pytaj
update.dlg.oa_overwrite = Z&astąp
update.dlg.oa_skip = &Omiń
update.dlg.enable_filter = Użyj &filtra
update.dlg.wrong_arc_type = Wybierz format archiwum
update.dlg.wrong_level = Wybierz poziom kompresji
update.dlg.wrong_method = Wybierz metodę kompresji
update.dlg.passwords_dont_match = Hasło nie pasuje
update.dlg.password_is_empty = Hasło jest puste
update.dlg.wrong_volume_size = Niewłaściwa wielkość wolumenu
update.dlg.confirm_overwrite = Plik docelowy już istnieje. Zastąpić go?
update.dlg.input_profile_name = Podaj nazwę profilu
update.dlg.confirm_profile_delete = Chcesz usunąć zaznaczony profil?
update.dlg.sfx_no_ppmd = Wybrany SFX nie obsługuje kompresji PPMD
update.dlg.sfx_no_encrypt = Wybrany SFX nie obsługuje szyfrowania
update.dlg.save_params = Zapisz ustawienia
update.dlg.params_saved = Ustawienia zapisane

# Archive types
compression.archive.7z = &7z
compression.archive.zip = &Zip

# Compression levels
compression.level.store = Zapisz
compression.level.fastest = Najszybsza
compression.level.fast = Szybka
compression.level.normal = Normalna
compression.level.maximum = Maksymalna
compression.level.ultra = Ultra

# Compression methods
compression.method.lzma = LZMA
compression.method.lzma2 = LZMA2
compression.method.ppmd = PPMD

# Delete files
delete.dlg.confirm = Chcesz usunąć zaznaczone pliki?

# Create directory
create_dir.dlg.name = Podaj nazwę folderu:

# Test archive
test.ok = Test zakończony poprawnie
test.menu = Test archiwum plików

# Password dialog
password.title = Podaj hasło
password.password = Hasło:

# Overwrite dialog
overwrite.dlg.title = Zastąp plik
overwrite.dlg.question = Plik docelowy już istnieje. Zastąpić?
overwrite.dlg.source = Źródło:
overwrite.dlg.destination = Cel:
overwrite.dlg.newer = (nowszy)
overwrite.dlg.all = &Pamiętaj wybór
overwrite.dlg.overwrite = Z&astąp
overwrite.dlg.skip = &Omiń
overwrite.dlg.rename = &Zmień nazwę
overwrite.dlg.append = &Dołącz
overwrite.dlg.cancel = &Anuluj

# Error retry dialog
button.retry = &Ponów
button.ignore = &Ignoruj
button.ignore_all = Ign.&wszystko

# Log dialog
log.title = Dziennik zdarzeń
log.info = Operacja zakończona z błędami. Chcesz zobaczyć dziennik?
log.close = &Zamknij
log.show = &Pokaż dziennik

# Settings dialog
settings.dlg.handle_create = Przejmij tworzenie archiwów (Shift-F&1)
settings.dlg.handle_commands = Przejmij obsługę archiwów (Ctrl-PgDn, Shift-F&2)
settings.dlg.own_panel_view_mode = &Użyj własnego trybu podglądu
settings.dlg.oem_codepage = &Strona kodowa OEM:
settings.dlg.ansi_codepage = Strona kodowa &ANSI:
settings.dlg.save_codepage = Zapisz stronę &kodową
settings.dlg.use_include_masks = &Otwieraj pliki z maskami:
settings.dlg.use_exclude_masks = &Wyklucz pliki z maskami:
settings.dlg.pgdn_masks = Uży&j masek dla Ctrl-PgDn
settings.dlg.generate_masks = &Generuj maski
settings.dlg.default_masks = Domyślne &maski
settings.dlg.use_enabled_formats = Włą&cz formaty archiwów:
settings.dlg.use_disabled_formats = W&yłącz formaty archiwów:
settings.dlg.pgdn_formats = Użyj &formatów dla Ctrl-PgDn
settings.dlg.lib_info = Info o bibliotece &7z
settings.dlg.lib_not_found = Brak biblioteki 7z
settings.dlg.lib_version = Wersja:
settings.dlg.lib_formats = Formaty
settings.dlg.lib_masks = Maski
settings.dlg.active = Aktywne
settings.dlg.edit = Edycja

# Attributes dialog
attr.dlg.title = Atrybuty

# SFX options dialog
sfx_options.dlg.title = Opcje SFX
sfx_options.dlg.profile = Zastosuj &profil:
sfx_options.dlg.module = Nazwa &modułu:
sfx_options.dlg.replace_icon = Zamień &ikonę
sfx_options.dlg.icon_path = Ścieżka do ikon&y:
sfx_options.dlg.replace_version = Zastąp &wersję
sfx_options.dlg.ver_info.version = W&ersja:
sfx_options.dlg.ver_info.comments = &Komentarz:
sfx_options.dlg.ver_info.company_name = Nazwa &firmy:
sfx_options.dlg.ver_info.file_description = &Opis pliku:
sfx_options.dlg.ver_info.legal_copyright = P&rawa autorskie:
sfx_options.dlg.ver_info.product_name = &Nazwa produktu:
sfx_options.dlg.append_install_config = &Konfig. instalatora
sfx_options.dlg.install_config.title = &Tytuł:
sfx_options.dlg.install_config.begin_prompt = Tekst zachęty:
sfx_options.dlg.install_config.progress = Pa&sek postępu:
sfx_options.dlg.install_config.run_program = &Uruchom program:
sfx_options.dlg.install_config.directory = Fol&der:
sfx_options.dlg.install_config.execute_file = Uru&chom plik:
sfx_options.dlg.install_config.execute_parameters = P&arametry uruch.:
sfx_options.dlg.wrong_module = Wybierz moduł SFX
sfx_options.dlg.invalid_icon_path = Nieprawidłowa ścieżka do ikony

# SFX module description
sfx_descr.7z = Standard GUI
sfx_descr.7zcon = Standardowa konsola
sfx_descr.7zs = Instalator GUI (statyczny)
sfx_descr.7zs2 = Mały instalator GUI
sfx_descr.7zs2con = Mały instalator konsoli
sfx_descr.7zsd = Instalator GUI
sfx_descr.unknown = Nieznany

# Plugin menu
menu.open = &Otwórz archiwum
menu.detect = Otwórz (&format menu)
menu.create = &Utwórz archiwum
menu.extract = &Rozpakuj archiwum
menu.test = &Test archiwum
menu.sfx_convert = &Konwertuj archiwum do SFX

# Progress messages
progress.open = Czytanie archiwum...
progress.extract = Rozpakowanie plików...
progress.create_dirs = Tworzenie folderów...
progress.set_attr = Ustawiam atrybuty...
progress.test = Testuję archiwum...
progress.update = Aktualizuję archiwum...
progress.create = Tworzenie archiwum...
progress.delete_files = Usuwanie plików...
progress.scan_dirs = Skanuję foldery...
progress.interrupt = Chcesz przerwać bieżącą operację?
progress.paused = Wstrzymano
progress.low_priority = Niski
progress.sfx_convert = Konwertuję do SFX...

# Error messages
error.extract.unsupported_method = Nieobsługiwany sposób kompresji
error.extract.data_error = Błąd danych
error.extract.data_error.encrypted = Złe hasło lub błąd danych
error.extract.crc_error = Błąd sprawdzania CRC
error.extract.crc_error.encrypted = Złe hasło lub błąd CRC
error.extract.unavailable_data = Dane niedostępne
error.extract.unexpected_end_data = Niespodziewany koniec danych
error.extract.data_after_end = Istnieją jakieś dane na końcu archiwum
error.extract.is_not_archive = To nie jest archiwum
error.extract.headers_error = Błąd nagłówka
error.extract.wrong_password = Złe hasło
error.extract.unknown = Nieznany błąd rozpakowania
error.update.error = Błąd aktualizacji
error.update.unknown = Nieznany błąd aktualizacji
error.no_format = Nie znaleziono formatu archiwum
error.not_updatable = Modyfikacja archiwum nie jest obsługiwana
error.not_archive = Plik nie jest archiwum
error.sfx_convert = Archiwum nie może być przekonwertowane na format SFX
error.update.unsupported_for_singlefilearchive = Nie można zmienić typu archiwum

# Generic buttons
button.ok = OK
button.cancel = Anuluj

# Size and speed suffixes
suffix.size.b = B
suffix.size.kb = KB
suffix.size.mb = MB
suffix.size.gb = GB
suffix.size.tb = TB
suffix.speed.b = B/s
suffix.speed.kb = KB/s
suffix.speed.mb = MB/s
suffix.speed.gb = GB/s
suffix.speed.tb = TB/s

# Property names
kpid.Path = Ścieżka
kpid.Name = Nazwa
kpid.Extension = Rozszerzenie
kpid.IsDir = Folder
kpid.Size = Wielkość
kpid.PackSize = Spak. wielk.
kpid.Attrib = Atrybuty
kpid.CTime = Utworzono
kpid.ATime = Accessed
kpid.MTime = Zmodyfikowano
kpid.Solid = Solidne
kpid.Commented = Komentarz
kpid.Encrypted = Zaszyfrowane
kpid.SplitBefore = Podziel przed
kpid.SplitAfter = Podziel po
kpid.DictionarySize = Słownik
kpid.CRC = CRC
kpid.Type = Typ
kpid.IsAnti = Anti
kpid.Method = Metoda
kpid.HostOS = Host OS
kpid.FileSystem = System plików
kpid.User = Użytownik
kpid.Group = Grupa
kpid.Block = Blok
kpid.Comment = Komentarz
kpid.Position = Pozycja
kpid.Prefix = Przedrostek ścieżki
kpid.NumSubDirs = Foldery
kpid.NumSubFiles = Pliki
kpid.UnpackVer = Wersja
kpid.Volume = Wolumen
kpid.IsVolume = Wielowolumen
kpid.Offset = Przesunięcie
kpid.Links = Linki
kpid.NumBlocks = Bloki
kpid.NumVolumes = Wolumeny
kpid.TimeType = Typ czasu
kpid.Bit64 = 64-bit
kpid.BigEndian = Big-endian
kpid.Cpu = CPU
kpid.PhySize = Fizyczna wielkość
kpid.HeadersSize = Wielk. nagłówka
kpid.Checksum = Suma kontrolna
kpid.Characts = Charakterystyka
kpid.Va = Adres wirtualny
kpid.Id = ID
kpid.ShortName = Krótka nazwa
kpid.CreatorApp = Aplikacja tworząca
kpid.SectorSize = Wielkość sektora
kpid.PosixAttrib = Tryb
kpid.Link = Link symboliczny
kpid.Error = Błąd
kpid.TotalSize = Całkowita wielkość
kpid.FreeSpace = Wolne miejsce
kpid.ClusterSize = Wielkość klastra
kpid.VolumeName = Etykieta
kpid.LocalName = Nazwa lokalna
kpid.Provider = Dostawca
kpid.NtSecure = Zabezpieczenie NT
kpid.IsAltStream = Alternatywny strumień
kpid.IsAux = Aux
kpid.IsDeleted = Usunięte
kpid.IsTree = To drzewo
kpid.Sha1 = SHA-1
kpid.Sha256 = SHA-256
kpid.ErrorType = Błąd typu
kpid.NumErrors = Błędy
kpid.ErrorFlags = Błędy
kpid.WarningFlags = Uwagi
kpid.Warning = Uwaga
kpid.NumStreams = Strumienie
kpid.NumAltStreams = Altern.strumienie
kpid.AltStreamsSize = Wielkość alt.strumieni
kpid.VirtualSize = Wirtualna wielkość
kpid.UnpackSize = Wielkość po rozpakowaniu
kpid.TotalPhySize = Całkowita fizyczna wielkość
kpid.VolumeIndex = Indeks wolumenu
kpid.SubType = PodTyp
kpid.ShortComment = Krótki komentarz
kpid.CodePage = Strona kodowa
kpid.IsNotArcType = To jest typ archiwum
kpid.PhySizeCantBeDetected = Nie można wykryć całkowitej wielkości
kpid.ZerosTailIsAllowed = Zeros Tail Is Allowed
kpid.TailSize = Tail Size
kpid.EmbeddedStubSize = Embedded Stub Size
kpid.NtReparse = Link
kpid.HardLink = Twardy link
kpid.INode = iNode
kpid.StreamId = ID strumienia
kpid.ReadOnly = Tylko-odczyt
kpid.OutName = Nazwa docelowa
kpid.CopyLink = Link kopii

# Property values
property.true = Tak
property.false = Nie
property.compression_ratio = Stopień kompresji
property.total_size = Wielkość danych
property.total_packed_size = Spakowane
property.file_count = Plików
property.dir_count = Folderów
