.Language=Polish,Polish (Polski)

lang = pl
plugin.name = <(NAME)>

# Extract dialog
extract.dlg.title = Rozpakuj pliki
extract.dlg.dst_dir = &Rozpakuj pliki do:
extract.dlg.ignore_errors = &Ignoruj błędy
extract.dlg.oa = When destination file exists:
extract.dlg.oa_ask = As&k
extract.dlg.oa_overwrite = &Overwrite
extract.dlg.oa_skip = &Omiń
extract.dlg.oa_rename = &Rename
extract.dlg.oa_append = &Dołącz
extract.dlg.move_files = &Delete files from archive after extraction
extract.dlg.password = Pass&word:
extract.dlg.separate_dir = Ex&tract archive into separate directory
extract.dlg.delete_archive = &Usuń archiwum po rozpakowaniu
extract.dlg.open_dir = &Go to target directory after extraction
extract.dlg.save_params = Sa&ve settings
extract.dlg.params_saved = Ustawienia zapisane

# Update dialog
update.dlg.title = Dodaj pliki do archiwum
update.dlg.title.create = Utwórz archiwum
update.dlg.profile = &Profil:
update.dlg.save_profile = Zapisz
update.dlg.delete_profile = Usuń
update.dlg.arc_path = Arc&hive path:
update.dlg.arc_path_eval = Eval&uate
update.dlg.append_ext = &Dołącz rozsz.
update.dlg.arc_type = Wybierz archiwizator:
update.dlg.arc_type.other = O&ther:
update.dlg.level = Compression &level:
update.dlg.method = &Method:
update.dlg.solid = S&olid
update.dlg.advanced = Advan&ced parameters:
update.dlg.encrypt = &Encrypt archive
update.dlg.show_password = Pokaż hasło
update.dlg.password = &Hasło:
update.dlg.password2 = Powtórz:
update.dlg.encrypt_header = Zaszyfruj nagłówek
update.dlg.create_sfx = Create self-e&xtracting archive
update.dlg.sfx_options = Opcje SFX
update.dlg.enable_volumes = Podziel na &wolumeny
update.dlg.volume_size = Wielk. wolumenu:
update.dlg.move_files = &Delete files after archiving
update.dlg.open_shared = Archive files open for w&riting
update.dlg.ignore_errors = &Ignore errors
update.dlg.oa = Gdy plik docelowy istnieje:
update.dlg.oa_ask = As&k
update.dlg.oa_overwrite = O&verwrite
update.dlg.oa_skip = Ski&p
update.dlg.enable_filter = Użyj &filtra
update.dlg.wrong_arc_type = Wybierz format archiwum
update.dlg.wrong_level = Wybierz poziom kompresji
update.dlg.wrong_method = Wybierz metodę kompresji
update.dlg.passwords_dont_match = Hasło nie pasuje
update.dlg.password_is_empty = Hasło jest puste
update.dlg.wrong_volume_size = Niewłaściwa wielkość wolumenu
update.dlg.confirm_overwrite = Plik docelowy już istnieje. Zastąpić go?
update.dlg.input_profile_name = Podaj nazwę profilu
update.dlg.confirm_profile_delete = Chcesz usunąć zaznaczony profil?
update.dlg.sfx_no_ppmd = Wybrany SFX nie obsługuje kompresji PPMD
update.dlg.sfx_no_encrypt = Wybrany SFX nie obsługuje szyfrowania
update.dlg.save_params = Zapisz ustawienia
update.dlg.params_saved = Ustawienia zapisane

# Archive types
compression.archive.7z = &7z
compression.archive.zip = &zip

# Compression levels
compression.level.store = Zapisz
compression.level.fastest = Najszybsza
compression.level.fast = Szybka
compression.level.normal = Normalna
compression.level.maximum = Maksymalna
compression.level.ultra = Ultra

# Compression methods
compression.method.lzma = LZMA
compression.method.lzma2 = LZMA2
compression.method.ppmd = PPMD

# Delete files
delete.dlg.confirm = Chcesz usunąć zaznaczone pliki?

# Create directory
create_dir.dlg.name = Podaj nazwę folderu:

# Test archive
test.ok = Test zakończony poprawnie
test.menu = Test archiwum plików

# Password dialog
password.title = Podaj hasło
password.password = Hasło:

# Overwrite dialog
overwrite.dlg.title = Zastąp plik
overwrite.dlg.question = Pli docelowy już istnieje. Zastąpić?
overwrite.dlg.source = Źródło:
overwrite.dlg.destination = Cel:
overwrite.dlg.newer = (nowszy)
overwrite.dlg.all = &Remember choice
overwrite.dlg.overwrite = &Overwrite
overwrite.dlg.skip = &Skip
overwrite.dlg.rename = R&ename
overwrite.dlg.append = &Dołącz
overwrite.dlg.cancel = &Cancel

# Error retry dialog
button.retry = &Ponów
button.ignore = &Ignoruj
button.ignore_all = Ignore &All

# Log dialog
log.title = Operation log
log.info = Operation completed with errors. Do you want to review log file?
log.close = &Close
log.show = Show &log

# Settings dialog
settings.dlg.handle_create = Handle archive creation (Shift-F&1)
settings.dlg.handle_commands = Handle archive commands (Ctrl-PgDn, Shift-F&2)
settings.dlg.own_panel_view_mode = Use o&wn panel view mode
settings.dlg.oem_codepage = OEM &Codepage:
settings.dlg.ansi_codepage = Strona kodowa &ANSI:
settings.dlg.save_codepage = Sa&ve Codepages
settings.dlg.use_include_masks = &Open files matching masks:
settings.dlg.use_exclude_masks = &Exclude files matching masks:
settings.dlg.pgdn_masks = Ma&sk settings apply to Ctrl-PgDn
settings.dlg.generate_masks = &Generate masks
settings.dlg.default_masks = Domyślne &maski
settings.dlg.use_enabled_formats = E&nable archive formats:
settings.dlg.use_disabled_formats = &Disable archive formats:
settings.dlg.pgdn_formats = &Format settings apply to Ctrl-PgDn
settings.dlg.lib_info = &7z library info
settings.dlg.lib_not_found = Brak biblioteki 7z
settings.dlg.lib_version = Wersja:
settings.dlg.lib_formats = Formaty
settings.dlg.lib_masks = Maski
settings.dlg.active = Aktywne
settings.dlg.edit = Edycja

# Attributes dialog
attr.dlg.title = Atrybuty

# SFX options dialog
sfx_options.dlg.title = SFX Options
sfx_options.dlg.profile = Apply &profile:
sfx_options.dlg.module = &Module name:
sfx_options.dlg.replace_icon = Replace &icon
sfx_options.dlg.icon_path = Icon pat&h:
sfx_options.dlg.replace_version = Replace &version
sfx_options.dlg.ver_info.version = V&ersion:
sfx_options.dlg.ver_info.comments = &Comments:
sfx_options.dlg.ver_info.company_name = C&ompany name:
sfx_options.dlg.ver_info.file_description = File &description:
sfx_options.dlg.ver_info.legal_copyright = &Legal copyright:
sfx_options.dlg.ver_info.product_name = Product &name:
sfx_options.dlg.append_install_config = In&stall configuration
sfx_options.dlg.install_config.title = &Tytuł:
sfx_options.dlg.install_config.begin_prompt = &Begin prompt:
sfx_options.dlg.install_config.progress = Pro&gress meter:
sfx_options.dlg.install_config.run_program = &Run program:
sfx_options.dlg.install_config.directory = Director&y:
sfx_options.dlg.install_config.execute_file = E&xecute file:
sfx_options.dlg.install_config.execute_parameters = Execute p&arameters:
sfx_options.dlg.wrong_module = Wybierz moduł SFX
sfx_options.dlg.invalid_icon_path = Nieprawidłowa ścieżka do ikony

# SFX module description
sfx_descr.7z = Standard GUI
sfx_descr.7zcon = Standard console
sfx_descr.7zs = Installer GUI (static)
sfx_descr.7zs2 = Small installer GUI
sfx_descr.7zs2con = Small installer console
sfx_descr.7zsd = Installer GUI
sfx_descr.unknown = Nieznany

# Plugin menu
menu.open = &Open archive
menu.detect = Open (&format menu)
menu.create = &Create archive
menu.extract = &Extract archive(s)
menu.test = &Test archive(s)
menu.sfx_convert = C&onvert archive into SFX

# Progress messages
progress.open = Czytanie archiwum...
progress.extract = Rozpakowanie plików...
progress.create_dirs = Tworzenie folderów...
progress.set_attr = Ustawiam atrybuty...
progress.test = Testuję archiwum...
progress.update = Aktualizuję archiwum...
progress.create = Tworzenie archiwum...
progress.delete_files = Usuwanie plików...
progress.scan_dirs = Skanuję foldery...
progress.interrupt = Do you want to interrupt current operation?
progress.paused = Wstrzymano
progress.low_priority = Low
progress.sfx_convert = Konwertuję do SFX...

# Error messages
error.extract.unsupported_method = Nieobsługiwany sposób kompresji
error.extract.data_error = Błąd danych
error.extract.data_error.encrypted = Złe hasło lub błąd danych
error.extract.crc_error = Błąd sprawdzania CRC
error.extract.crc_error.encrypted = Złe hasło lub błąd CRC
error.extract.unavailable_data = Dane niedostępne
error.extract.unexpected_end_data = Niezpodziewany koniec danych
error.extract.data_after_end = There are some data after the end of the payload data
error.extract.is_not_archive = To nie jest archiwum
error.extract.headers_error = Błąd nagłówka
error.extract.wrong_password = Złe hasło
error.extract.unknown = Nieznany błąd rozpakowania
error.update.error = Błąd aktualizacji
error.update.unknown = Nieznany błąd aktualizacji
error.no_format = Nie znaleziono formatu archiwum
error.not_updatable = Modyfikacja archiwum nie jest obsługiwana
error.not_archive = Plik nie jest archiwum
error.sfx_convert = Archiwum nie może być przekonwertowane na format SFX
error.update.unsupported_for_singlefilearchive = Can't change single file archive format

# Generic buttons
button.ok = OK
button.cancel = Anuluj

# Size and speed suffixes
suffix.size.b = B
suffix.size.kb = KB
suffix.size.mb = MB
suffix.size.gb = GB
suffix.size.tb = TB
suffix.speed.b = B/s
suffix.speed.kb = KB/s
suffix.speed.mb = MB/s
suffix.speed.gb = GB/s
suffix.speed.tb = TB/s

# Property names
kpid.Path = Path
kpid.Name = Name
kpid.Extension = Extension
kpid.IsDir = Folder
kpid.Size = Size
kpid.PackSize = Packed Size
kpid.Attrib = Attributes
kpid.CTime = Created
kpid.ATime = Accessed
kpid.MTime = Modified
kpid.Solid = Solid
kpid.Commented = Commented
kpid.Encrypted = Encrypted
kpid.SplitBefore = Split Before
kpid.SplitAfter = Split After
kpid.DictionarySize = Dictionary
kpid.CRC = CRC
kpid.Type = Typ
kpid.IsAnti = Anti
kpid.Method = Method
kpid.HostOS = Host OS
kpid.FileSystem = File System
kpid.User = Użytownik
kpid.Group = Group
kpid.Block = Block
kpid.Comment = Comment
kpid.Position = Position
kpid.Prefix = Path Prefix
kpid.NumSubDirs = Folders
kpid.NumSubFiles = Files
kpid.UnpackVer = Wersja
kpid.Volume = Wolumen
kpid.IsVolume = Multivolume
kpid.Offset = Offset
kpid.Links = Links
kpid.NumBlocks = Blocks
kpid.NumVolumes = Volumes
kpid.TimeType = Time Type
kpid.Bit64 = 64-bit
kpid.BigEndian = Big-endian
kpid.Cpu = CPU
kpid.PhySize = Physical Size
kpid.HeadersSize = Headers Size
kpid.Checksum = Checksum
kpid.Characts = Characteristics
kpid.Va = Adres wirtualny
kpid.Id = ID
kpid.ShortName = Short Name
kpid.CreatorApp = Creator Application
kpid.SectorSize = Sector Size
kpid.PosixAttrib = Mode
kpid.Link = Symbolic Link
kpid.Error = Error
kpid.TotalSize = Total Size
kpid.FreeSpace = Free Space
kpid.ClusterSize = Cluster Size
kpid.VolumeName = Etykieta
kpid.LocalName = Local Name
kpid.Provider = Provider
kpid.NtSecure = NT Security
kpid.IsAltStream = Alternate Stream
kpid.IsAux = Aux
kpid.IsDeleted = Deleted
kpid.IsTree = Is Tree
kpid.Sha1 = SHA-1
kpid.Sha256 = SHA-256
kpid.ErrorType = Error Type
kpid.NumErrors = Errors
kpid.ErrorFlags = Errors
kpid.WarningFlags = Uwagi
kpid.Warning = Uwaga
kpid.NumStreams = Streams
kpid.NumAltStreams = Alternate Streams
kpid.AltStreamsSize = Alternate Streams Size
kpid.VirtualSize = Wirtualna wielkość
kpid.UnpackSize = Unpack Size
kpid.TotalPhySize = Total Physical Size
kpid.VolumeIndex = Indeks wolumenu
kpid.SubType = SubType
kpid.ShortComment = Short Comment
kpid.CodePage = Code Page
kpid.IsNotArcType = Is not archive type
kpid.PhySizeCantBeDetected = Physical Size can't be detected
kpid.ZerosTailIsAllowed = Zeros Tail Is Allowed
kpid.TailSize = Tail Size
kpid.EmbeddedStubSize = Embedded Stub Size
kpid.NtReparse = Link
kpid.HardLink = Hard Link
kpid.INode = iNode
kpid.StreamId = Stream ID
kpid.ReadOnly = Read-only
kpid.OutName = Out Name
kpid.CopyLink = Copy Link

# Property values
property.true = Tak
property.false = No
property.compression_ratio = Stopień kompresji
property.total_size = Wielkość danych
property.total_packed_size = Spakowane
property.file_count = Plików
property.dir_count = Folderów