.Language=Spanish,Spanish (Español)

lang = es
plugin.name = <(NAME)>

# Extract dialog
extract.dlg.title = Extraer archivos
extract.dlg.dst_dir = &Extraer archivos a:
extract.dlg.ignore_errors = &Ignorar errores
extract.dlg.oa = Cuando archivo destino ya existe:
extract.dlg.oa_ask = &Preguntar
extract.dlg.oa_overwrite = S&obrescribir
extract.dlg.oa_skip = &Saltar
extract.dlg.oa_rename = &Renombrar
extract.dlg.oa_append = &Añadir
extract.dlg.move_files = Borrar archivos del archivo comprimido luego de extraer
extract.dlg.password = &Contraseña:
extract.dlg.separate_dir = Ex&traer archivos en directorios separados
extract.dlg.delete_archive = &Borrar archivo comprimido luego de la extracción
extract.dlg.open_dir = Ir a directorio destino luego de la extracción
extract.dlg.save_params = &Guardar ajustes
extract.dlg.params_saved = Ajustes guardados

# Update dialog
update.dlg.title = Añadir archivos al archivo comprimido
update.dlg.title.create = Crear archivo comprimido
update.dlg.profile = &Perfil:
update.dlg.save_profile = Guardar
update.dlg.delete_profile = Borrar
update.dlg.arc_path = Ruta de arc&hivo:
update.dlg.arc_path_eval = Eval&uar
update.dlg.append_ext = &Añadir extensión
update.dlg.arc_type = Seleccionar compresor:
update.dlg.arc_type.other = O&tro:
update.dlg.level = Nive&l de compresión: 
update.dlg.method = &Método:
update.dlg.solid = Sólid&o
update.dlg.advanced = Parámetros avan&zados:
update.dlg.encrypt = Ci&frar archivo
update.dlg.show_password = Mostrar contraseña
update.dlg.password = &Contraseña:
update.dlg.password2 = Repetir:
update.dlg.encrypt_header = Cifrar encabezamiento
update.dlg.create_sfx = Crear archivo auto-e&xtraíble
update.dlg.sfx_options = Opciones SFX
update.dlg.enable_volumes = Dividir en &volumenes
update.dlg.volume_size = Tamaño volumen:
update.dlg.move_files = &Borrar archivos luego de comprimirlos
update.dlg.open_shared = Archivos de arch. compr. abiertos a es&critura
update.dlg.ignore_errors = &Ignorar errores
update.dlg.oa = Cuando archivo destino ya existe:
update.dlg.oa_ask = &Preguntar
update.dlg.oa_overwrite = So&brescribir
update.dlg.oa_skip = Sal&tar
update.dlg.enable_filter = Usar &filtro
update.dlg.wrong_arc_type = Seleccionar formato de compresión
update.dlg.wrong_level = Seleccionar nivel de compresión
update.dlg.wrong_method = Seleccionar método de compresión
update.dlg.passwords_dont_match = Contraseñas no coinciden
update.dlg.password_is_empty = Contraseña esta vacía
update.dlg.wrong_volume_size = Tamaño de volumen no es válido
update.dlg.confirm_overwrite = El archivo destino ya existe. Quiere sobrescribirlo?
update.dlg.input_profile_name = Ingresar nombre de perfil
update.dlg.confirm_profile_delete = Desea eliminar el perfil seleccionado?
update.dlg.sfx_no_ppmd = Módulo SFX seleccionado no soporta compresión PPMD
update.dlg.sfx_no_encrypt = Módulo SFX seleccionado no soporta cifrado
update.dlg.save_params = Guardar ajustes
update.dlg.params_saved = Ajustes guardados

# Archive types
compression.archive.7z = &7z
compression.archive.zip = &zip

# Compression levels
compression.level.store = Almacenar
compression.level.fastest = +Rápido
compression.level.fast = Rápido
compression.level.normal = Normal
compression.level.maximum = Máxima
compression.level.ultra = Ultra

# Compression methods
compression.method.lzma = LZMA
compression.method.lzma2 = LZMA2
compression.method.ppmd = PPMD

# Delete files
delete.dlg.confirm = Quiere borrar los archivos seleccionados?

# Create directory
create_dir.dlg.name = Ingresar nombre de directorio:

# Test archive
test.ok = Comprobación de archivo completada
test.menu = Comprobar archivo comprimido

# Password dialog
password.title = Ingresar contraseña
password.password = Contraseña:

# Overwrite dialog
overwrite.dlg.title = Sobrescribir archivo
overwrite.dlg.question = El archivo destino ya existe. Quiere Sobrescribirlo?
overwrite.dlg.source = Origen:
overwrite.dlg.destination = Destino:
overwrite.dlg.newer = (+nuevo)
overwrite.dlg.all = R&ecordar elección
overwrite.dlg.overwrite = S&obrescribir
overwrite.dlg.skip = &Saltar
overwrite.dlg.rename = &Renombrar
overwrite.dlg.append = &Anexar
overwrite.dlg.cancel = &Cancelar

# Error retry dialog
button.retry = &Reiterar
button.ignore = &Ignorar
button.ignore_all = Ignor&ar Todo

# Log dialog
log.title = Registro de operación
log.info = Operación completada con errores. Quiere revisar archivo registro?
log.close = &Cerrar
log.show = Mostrar &registro

# Settings dialog
settings.dlg.handle_create = Gestionar creación de archivo (Shift-F&1)
settings.dlg.handle_commands = Gestionar comandos de archivo (Ctrl-PgDn, Shift-F&2)
settings.dlg.own_panel_view_mode = Usar modo de vista &propio en panel
settings.dlg.oem_codepage = Página de códigos OEM:
settings.dlg.ansi_codepage = Página de códigos ANSI:
settings.dlg.save_codepage = Guardar página de códigos
settings.dlg.use_include_masks = Abrir máscaras archivos c&oincidentes:
settings.dlg.use_exclude_masks = Máscaras de archivos a &excluir:
settings.dlg.pgdn_masks = Aplicar ajustes de má&scara a Ctrl-PgDn
settings.dlg.generate_masks = &Generar máscaras
settings.dlg.default_masks = &Máscaras por defecto
settings.dlg.use_enabled_formats = Activar formatos de archivos:
settings.dlg.use_disabled_formats = &Desactivar formatos de archivos:
settings.dlg.pgdn_formats = Aplicar ajustes de &formato a Ctrl-PgDn
settings.dlg.lib_info = Info de libreria &7z
settings.dlg.lib_not_found = Libreria 7z no fue encontrada
settings.dlg.lib_version = Versión:
settings.dlg.lib_formats = Formatos
settings.dlg.lib_masks = Máscaras
settings.dlg.active = Activo
settings.dlg.edit = Editar

# Attributes dialog
attr.dlg.title = Atributos

# SFX options dialog
sfx_options.dlg.title = Opciones SFX
sfx_options.dlg.profile = Aplicar &perfil:
sfx_options.dlg.module = Nombre &módulo:
sfx_options.dlg.replace_icon = Reemplazar &iconos
sfx_options.dlg.icon_path = Ruta ícono:
sfx_options.dlg.replace_version = Reemplazar &versión
sfx_options.dlg.ver_info.version = V&ersión:
sfx_options.dlg.ver_info.comments = &Comentarios:
sfx_options.dlg.ver_info.company_name = Nombre c&ompañia:
sfx_options.dlg.ver_info.file_description = &Descripción archivo:
sfx_options.dlg.ver_info.legal_copyright = Copyright &legal:
sfx_options.dlg.ver_info.product_name = &Nombre producto:
sfx_options.dlg.append_install_config = In&stalar configuración
sfx_options.dlg.install_config.title = &Título:
sfx_options.dlg.install_config.begin_prompt = Ini&cio de Prompt:
sfx_options.dlg.install_config.progress = Medidor pro&greso:
sfx_options.dlg.install_config.run_program = Ejecutar p&rograma:
sfx_options.dlg.install_config.directory = Director&io:
sfx_options.dlg.install_config.execute_file = E&jecutar archivo:
sfx_options.dlg.install_config.execute_parameters = Ejecutar p&arámetros:
sfx_options.dlg.wrong_module = Seleccionar módulo SFX
sfx_options.dlg.invalid_icon_path = Ruta de ícono no es válida

# SFX module description
sfx_descr.7z = GUI estándar
sfx_descr.7zcon = Consola estándar
sfx_descr.7zs = GUI de instalación (estático)
sfx_descr.7zs2 = GUI de instalación pequeño
sfx_descr.7zs2con = Consola pequeña instalación
sfx_descr.7zsd = GUI instalador
sfx_descr.unknown = Desconocido

# Plugin menu
menu.open = Abrir archiv&o
menu.detect = Abrir (menú de &formatos)
menu.create = &Crear archivo comprimido
menu.extract = &Extraer archivo(s)
menu.test = Comprobar archivo(s)
menu.sfx_convert = C&onvertir archivo en SFX (autoextraíble)

# Progress messages
progress.open = Leyendo archivo comprimido...
progress.extract = Extrayendo archivos...
progress.create_dirs = Creando directorios...
progress.set_attr = Poniendo atributos...
progress.test = Comprobando archivo comprimido...
progress.update = Actualizando archivo comprimido...
progress.create = Creando archivo comprimido...
progress.delete_files = Eliminando archivos...
progress.scan_dirs = Explorando directorios...
progress.interrupt = Desea interrumpir la operación actual?
progress.paused = Pausado
progress.low_priority = Bajo
progress.sfx_convert = Convirtiendo en SFX...

# Error messages
error.extract.unsupported_method = Método de compresión no soportado
error.extract.data_error = Error de datos
error.extract.data_error.encrypted = Contraseña incorrecta o error de datos
error.extract.crc_error = Comprobación de CRC ha fallado
error.extract.crc_error.encrypted = Contraseña incorrecta o fallo de comprobación CRC
error.extract.unavailable_data = Datos no disponibles
error.extract.unexpected_end_data = Finalización de datos inesperado
error.extract.data_after_end = Hay algunos datos de carga útil después de la finalización de datos
error.extract.is_not_archive = No es un archivo comprimido
error.extract.headers_error = Error de encabezados
error.extract.wrong_password = Contraseña incorrecta
error.extract.unknown = Error de extracción desconocido
error.update.error = Error de actualización
error.update.unknown = Error de actualización desconocido
error.no_format = Formato de archivo no encontrado
error.not_updatable = Modificación de archivo no soportada
error.not_archive = Archivo no se reconoce como archivo comprimido
error.sfx_convert = El archivo no puede ser convertido en archivo SFX (autoextraíble)
error.update.unsupported_for_singlefilearchive = Can't change single file archive format

# Generic buttons
button.ok = Aceptar
button.cancel = Cancelar

# Size and speed suffixes
suffix.size.b = B
suffix.size.kb = KB
suffix.size.mb = MB
suffix.size.gb = GB
suffix.size.tb = TB
suffix.speed.b = B/s
suffix.speed.kb = KB/s
suffix.speed.mb = MB/s
suffix.speed.gb = GB/s
suffix.speed.tb = TB/s

# Property names
kpid.Path = Ruta
kpid.Name = Nombre
kpid.Extension = Extensión
kpid.IsDir = Es Carpeta
kpid.Size = Tamaño
kpid.PackSize = Tamaño Compresión
kpid.Attrib = Atributos
kpid.CTime = Creado
kpid.ATime = Accedido
kpid.MTime = Modificado
kpid.Solid = Sólido
kpid.Commented = Comentado
kpid.Encrypted = Cifrado
kpid.SplitBefore = Dividido Antes
kpid.SplitAfter = Dividido Luego
kpid.DictionarySize = Tamaño Diccionario
kpid.CRC = CRC
kpid.Type = Tipo
kpid.IsAnti = Anti
kpid.Method = Método
kpid.HostOS = OS de Servidor
kpid.FileSystem = Sistema de Archivo
kpid.User = Usuario
kpid.Group = Grupo
kpid.Block = Bloque
kpid.Comment = Comentario
kpid.Position = Posición
kpid.Prefix = Prefijo
kpid.NumSubDirs = Carpetas
kpid.NumSubFiles = Archivos
kpid.UnpackVer = Versión
kpid.Volume = Volumen
kpid.IsVolume = Multivolumen
kpid.Offset = Offset
kpid.Links = Enlaces
kpid.NumBlocks = Bloques
kpid.NumVolumes = Volumenes
kpid.TimeType = Tipo de Fecha/Hora
kpid.Bit64 = 64-bit
kpid.BigEndian = Big-endian
kpid.Cpu = CPU
kpid.PhySize = Tamaño Físico
kpid.HeadersSize = Tamaño Encabezamiento
kpid.Checksum = Checksum
kpid.Characts = Caracteristicas
kpid.Va = Dirección Virtual
kpid.Id = ID
kpid.ShortName = Nombre Corto
kpid.CreatorApp = Aplicación de Creación
kpid.SectorSize = Tamaño Sector
kpid.PosixAttrib = Modo
kpid.Link = Enlace
kpid.Error = Error
kpid.TotalSize = Tamaño Total
kpid.FreeSpace = Espacio Libre
kpid.ClusterSize = Tamaño Cluster
kpid.VolumeName = Etiqueta
kpid.LocalName = Nombre Local
kpid.Provider = Proveedor
kpid.NtSecure = NT Security
kpid.IsAltStream = Alternate Stream
kpid.IsAux = Aux
kpid.IsDeleted = Deleted
kpid.IsTree = Is Tree
kpid.Sha1 = SHA-1
kpid.Sha256 = SHA-256
kpid.ErrorType = Error Type
kpid.NumErrors = Errors
kpid.ErrorFlags = Errors
kpid.WarningFlags = Warnings
kpid.Warning = Warning
kpid.NumStreams = Streams
kpid.NumAltStreams = Alternate Streams
kpid.AltStreamsSize = Alternate Streams Size
kpid.VirtualSize = Virtual Size
kpid.UnpackSize = Unpack Size
kpid.TotalPhySize = Total Physical Size
kpid.VolumeIndex = Volume Index
kpid.SubType = SubType
kpid.ShortComment = Short Comment
kpid.CodePage = Code Page
kpid.IsNotArcType = Is not archive type
kpid.PhySizeCantBeDetected = Physical Size can't be detected
kpid.ZerosTailIsAllowed = Zeros Tail Is Allowed
kpid.TailSize = Tail Size
kpid.EmbeddedStubSize = Embedded Stub Size
kpid.NtReparse = Link
kpid.HardLink = Hard Link
kpid.INode = iNode
kpid.StreamId = Stream ID
kpid.ReadOnly = Read-only
kpid.OutName = Out Name
kpid.CopyLink = Copy Link

# Property values
property.true = Si
property.false = No
property.compression_ratio = Tasa de compresión
property.total_size = Tamaño de datos
property.total_packed_size = Tamaño de compresión
property.file_count = Conteo archivo
property.dir_count = Conteo directorio
