#include <farversion.hpp>

#define PLUGIN_BUILD 345
#define PLUGIN_DESC L"Archive support for Far Manager (based on 7-Zip project)"
#define PLUGIN_NAME L"ArcLite"
#define PLUGIN_FILENAME L"arclite.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
