LIBROOT    = D:\MYWIN\Far\PLUGINS\StdPlugins
PNAME      = ftpProgress
PROJECT    = ..\$(PNAME).fll
PDEF       = ..\def.def
PRES       = res.res
MAPFILE    = ..\$(PNAME).map
PRESFILES  =
NODYNDLL   = y
#DEBUG      =
CFLAG_ADD  = -x-
LFLAG_ADD  =

POBJS      = ..\p_All.obj \
             p_Main.obj p_cbFmt.obj p_TraficCB.obj p_Utils.obj

# ---------------------------------------------------------------------------
startup: _all
!include "../make_defs.bcb"
_all: $(PROJECT)
