#include <farversion.hpp>

#define PLUGIN_BUILD 57
#define PLUGIN_DESC L"Advanced File Compare for Far Manager"
#define PLUGIN_NAME L"Compare"
#define PLUGIN_FILENAME L"Compare.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
