enum
{
    MMacroMenu,
    MMacroConfig,

    MMacroTitle,
    MMacroTitleDS,
    MMacroBottom,

    MMacroError,
    MMacroWarning,
    MMacroExport,

    MMacroErrorRead,
    MMacroErrorWrite,
    MMacroErrorData,
    MMacroErrorCopy,
    MMacroErrorMove,
    MMacroErrorRun,
    MMacroErrorCreateTemp,
    MMacroErrorReadTemp,
    MMacroErrorCreateFolder,
    MMacroErrorCreateFile,
    MMacroErrorSelectConfiguration,

    MMacroWarningDelete,
    MMacroWarningEdit,
    MMacroCopy,
    MMacroMove,
    MMacroCopyMoveTo,
    MMacroNewKey,
    MMacroExportKey,
    MMacroExportAllKey,
    MMacroSaveToFile,
    MMacroInsertEditor,

    MMacroWhere,
    MMacroAllWhere,
    MMacroErrorInsertStrEditor,

    MMacroWarningDeleteKey,
    MMacroWarningDeleteThisKey,
    MMacroWarningDel,
    MMacroWarningRest,
    MMacroWarningInsertEmpty0,
    MMacroWarningInsertEmpty1,
    MMacroWarningInsertEmpty2,
    MMacroWarningEditThisKey,
    MMacroWarningExist,
    MMacroWarningFileExists,

    MMacroCombination,

    MMacroKey,
    MMacroGroup,
    MMacroCommand,
    MMacroDescription,
    MMacroRunAfterStart,
    MMacroDisable,
    MMacroAPanel,
    MMacroPPanel,
    MMacroFilePlugPanel,
    MMacroFolderFileUnder,
    MMacroFolderFileSelected,
    MMacroComState,
    MMacroSelection,
    MMacroSendToPlugins,

	// List of long area names of macros
    MMacroNameDialog,
    MMacroNameDisks,
    MMacroNameEditor,
    MMacroNameHelp,
    MMacroNameInfoPanel,
    MMacroNameMainMenu,
    MMacroNameMenu,
    MMacroNameQviewPanel,
    MMacroNameSearch,
    MMacroNameShell,
    MMacroNameTreePanel,
    MMacroNameViewer,
    MMacroNameOther,
    MMacroNameCommon,
    MMacroNameFindFolder,
    MMacroNameUserMenu,
    MMacroNameAutoCompletion,
	// End of list of long areas names

    MMacroSwitchOff,

    MMacroAddDescription,
    MMacroAutomaticSave,
    MMacroUseHighlight,
    MMacroStartDependentSort,
    MMacroLongGroupNames,
    MMacroMenuCycle,
    MMacroDblClick,
    MMacroGroupDivider,
    MMacroSaveOnStart,
    MMacroViewShell,
    MMacroViewViewer,
    MMacroViewEditor,

    MMacroOk,
    MMacroSave,
    MMacroCheck,
    MMacroDelete,
    MMacroTmpDel,
    MMacroTmpRest,
    MMacroCancel,
    MMacroOverwrite,
    MMacroRename,

    MMacroDestination,
    MMacroDefaultConfig,
    MMacroSelectConfig,

    MMacroKBHelp,
    MMacroKBSave,
    MMacroKBAltSaveAll,
    MMacroKBEdit,
    MMacroKBCopy,
    MMacroKBMove,
    MMacroKBQuit,

    MMacroDefineTitle,
    MMacroDesiredKey,
};
