#include "farversion.hpp"

#define PLUGIN_BUILD 17
#define PLUGIN_DESC L"Auto wrap for FAR Manager"
#define PLUGIN_NAME L"AutoWrap"
#define PLUGIN_FILENAME L"AutoWrap.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,PLUGIN_BUILD)
