#include <farversion.hpp>

#define PLUGIN_BUILD 1
#define PLUGIN_DESC L"Example"
#define PLUGIN_NAME L"example"
#define PLUGIN_FILENAME L"example"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
