#include <farversion.hpp>

#define PLUGIN_BUILD 50
#define PLUGIN_DESC L"Hlf-file Viewer for Far Manager"
#define PLUGIN_NAME L"HlfViewer"
#define PLUGIN_FILENAME L"HlfViewer.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
