#include "farversion.hpp"

#define PLUGIN_BUILD 30
#define PLUGIN_DESC L"Hlf-file Viewer for FAR Manager"
#define PLUGIN_NAME L"HlfViewer"
#define PLUGIN_FILENAME L"HlfViewer.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD)
