enum
{
  MOk,
  MCancel,
  MError,

  MNetMenu,

  MDiskMenuString,

  MF5,
  MF6,
  MF8,

  MNetCannotBrowse,
  MNetCannotConnect,
  MAlreadyRemembered,

  MOpenFiles,
  MAskDisconnect,
  MNetCannotDisconnect,

  MNoFreeLetters,

  MNetUserName,
  MNetUserPassword,

  MDisksListTitle,

  MNetwork,
  MColumnName,
  MColumnDisk,
  MColumnComment,

  MConfigTitle,
  MConfigAddToDisksMenu,
  MConfigDisksMenuDigit,
  MConfigSkipTopLevel,
};
