#include <farversion.hpp>

#define PLUGIN_BUILD 103
#define PLUGIN_DESC L"Network Plugin for Far Manager"
#define PLUGIN_NAME L"Network"
#define PLUGIN_FILENAME L"Network.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
