# ---- user's settings -------------------------------------------------------

TARGET      = luamacro.dll
FAR_EXPORTS = OPEN
PATH_LUAFAR = ../../luafar_unicode

# ---- end of user's settings ------------------------------------------------

include $(PATH_LUAFAR)/src/luaplug.mak

# (end of Makefile)
