#include <farversion.hpp>

#define PLUGIN_BUILD 1
#define PLUGIN_DESC L"Same Folder for Far Manager"
#define PLUGIN_NAME L"SameFolder"
#define PLUGIN_FILENAME L"SameFolder.dll"
#define PLUGIN_AUTHOR L"Far Group"
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
