#include <farversion.hpp>

#define PLUGIN_BUILD 0
#define PLUGIN_DESC L"customact"
#define PLUGIN_NAME L"customact"
#define PLUGIN_FILENAME L"customact.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
