#include <farversion.hpp>

#define PLUGIN_BUILD 27
#define PLUGIN_DESC L"Draw lines for Far Manager"
#define PLUGIN_NAME L"DrawLine"
#define PLUGIN_FILENAME L"DrawLine.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
