#include <farversion.hpp>

#define PLUGIN_BUILD 36
#define PLUGIN_DESC L"Brackets matching for Far Manager"
#define PLUGIN_NAME L"Brackets"
#define PLUGIN_FILENAME L"Brackets.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
