#include "farversion.hpp"

#define PLUGIN_BUILD 17
#define PLUGIN_DESC "Align block for FAR Manager"
#define PLUGIN_NAME "Align"
#define PLUGIN_FILENAME "Align.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,PLUGIN_BUILD)
