#include "farversion.hpp"

#define PLUGIN_BUILD 22
#define PLUGIN_DESC L"Align block for Far Manager"
#define PLUGIN_NAME L"Align"
#define PLUGIN_FILENAME L"Align.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,PLUGIN_BUILD)
