@echo off
mkdir ..\o
mkdir ..\o\newarc
mkdir ..\o\plugins
mkdir ..\o\plugins\ma
mkdir ..\o\plugins\rar
mkdir ..\o\plugins\targz
mkdir ..\o\plugins\zip
mkdir ..\o\plugins\7z
mkdir ..\o\rtl
mkdir ..\bin
mkdir ..\bin\plugins
mkdir ..\bin\plugins\ma
mkdir ..\bin\plugins\ma\formats
