enum
{
  MOk,
  MCancel,
  MError,

  MPlistPanel,

  MColumnModule,
  MColumnPriority,
  MColumnTitle,

  MBits,
  MTitleModule,
  MTitleFullPath,
  MTitlePID,
  MTitlePriority,
  MTitleThreads,
  MTitleStarted,
  MTitleUptime,
  MTitleCPUTime,
  MTitleKernelTime,
  MTitleUserTime,

  MTitleWindow,
  MTitleStyle,
  MTitleExtStyle,

  MDeleteTitle,
  MDeleteProcess,
  MDeleteProcesses,
  MDeleteNumberOfProcesses,
  MDeleteDelete,
  MCannotDelete,
};
