#ifndef VERSION_HPP_AFF7D87D_8E88_42B9_BFE5_A6CC301A086B
#define VERSION_HPP_AFF7D87D_8E88_42B9_BFE5_A6CC301A086B

#pragma once

#include <farversion.hpp>

#define PLUGIN_BUILD 210
#define PLUGIN_DESC L"Process List for FAR Manager"
#define PLUGIN_NAME L"ProcList"
#define PLUGIN_FILENAME L"ProcList.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)

#endif // VERSION_HPP_AFF7D87D_8E88_42B9_BFE5_A6CC301A086B
