#include "farversion.hpp"

#define PLUGIN_BUILD 166
#define PLUGIN_DESC L"Process List for FAR Manager"
#define PLUGIN_NAME L"ProcList"
#define PLUGIN_FILENAME L"ProcList.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
