LIBROOT    = D:\MYWIN\Far\PLUGINS\StdPlugins
PNAME      = ftpNotify
PROJECT    = ..\$(PNAME).fll
PDEF       = ..\def.def
PRES       = res.res
MAPFILE    = ..\$(PNAME).map
PRESFILES  =
NODYNDLL   = y
DEBUG      =
CFLAG_ADD  = /LD /GX- /GR- /J /Ob0
LFLAG_ADD  = #/noentry
CLIBS      =

POBJS      = ..\p_All.obj nt_Main.obj

# ---------------------------------------------------------------------------
startup: _all
!include "../make_defs.vc6"
_all: $(PROJECT)
