enum
{
    MConfig,
    MSetPassiveDir,
    MAddSetPassiveDir2PlugMenu,
    MAddToDisksMenu,
    MDisksMenuDigit,
    MSeparator,
    MHideCmdOutput,
    MKeepCmdOutput,
    MEchoCmdOutput,
    MCatchAllInOne,
    MCatchStdOutput,
    MCatchStdError,
    MCatchSeparate,
    MViewZeroFiles,
    MEditNewFiles,
    MStdOut,
    MStdErr,
    MOk,
    MCancel
};
