.path.obj = .
.path.c = .
.path.exe = .

RES = FARCmds.res
OBJS = FARCmds.obj
LIBS = cw32.lib import32.lib
#FLAGS = -X -4 -k- -K -w -O2 -Oc -Oi -RT- -a1 -x- -f- -ff- -I..\INCLUDE
FLAGS = -4 -k- -x- -f- -w -RT- -a2 -R- -M- -v- -I..\INCLUDE

!ifdef DEBUG
  DEFS  = -DDEBUG
!endif

!ifdef USE_BC_RTL
  OBJSS = c0d32.obj $(OBJS)
!else
  OBJSS = $(OBJS)
!endif

.c.obj:
  bcc32 -c $(FLAGS) $(DEFS) {$. }

.cpp.obj:
  bcc32 -c $(FLAGS) $(DEFS) {$. }

.rc.res:
  brcc32 -r $<

FARCmds.dll: $(OBJS) $(RES)
  tlink32 -x -OS -Tpd -aa -v- -P  @&&|
$(OBJSS)
$&
nul
$(LIBS)
,$(RES)
|
  @-del *.obj > nul
  @-del *.res > nul
  @-md FARCmds
  @-del FARCmds\FARCmds.dll > nul
  @-move \Progra~1\Far\Plugins\FARCmds\FARCmds.dll .\FARCmds\FARCmds.dll
  @copy FARCmds.dll "\Program Files\Far\Plugins\FARCmds\FARCmds.dll"
