#include "farversion.hpp"

#define PLUGIN_BUILD 129
#define PLUGIN_DESC L"FAR Commands Plugin for Far Manager"
#define PLUGIN_NAME L"FARCmds"
#define PLUGIN_FILENAME L"FARCmds.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
