#include <farversion.hpp>

#define PLUGIN_BUILD 37
#define PLUGIN_DESC L"File names case conversion for Far Manager"
#define PLUGIN_NAME L"FileCase"
#define PLUGIN_FILENAME L"FileCase.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
