#include "farversion.hpp"

#define PLUGIN_BUILD 39
#define PLUGIN_DESC L"EMenu Plugin for Far Manager"
#define PLUGIN_NAME L"EMenu"
#define PLUGIN_FILENAME L"EMenu.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,PLUGIN_BUILD)
