#include <farversion.hpp>

#define PLUGIN_BUILD 67
#define PLUGIN_DESC L"EMenu Plugin for Far Manager"
#define PLUGIN_NAME L"EMenu"
#define PLUGIN_FILENAME L"EMenu.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
