m4_include(`farversion.m4')m4_dnl
`#'define RC_MAJOR VERSION_MAJOR
`#'define RC_MINOR VERSION_MINOR
`#'define RC_BUILD VERSION_BUILD
`#'define RC_REVISION VERSION_REVISION
`#'define RC_FULLVERSION "FULLVERSION"
`#'define RC_COPYRIGHTYEAR "COPYRIGHTYEAR"
`#'define RC_PRIVATE BUILD_PRIVATE
`#'define RC_SPECIAL BUILD_SPECIAL
`#'define RC_PRERELEASE BUILD_PRERELEASE
`#'define RC_SPECIAL_STRING "VERSION_SPECIAL_STRING"
