m4_include(`farversion.m4')m4_dnl
m4_esyscmd(CMDAWK -f ./scripts/plugins.awk -v p1=M4_MACRO_GET(VERSION_MAJOR) -v p2=M4_MACRO_GET(VERSION_MINOR) -v p3=M4_MACRO_GET(VERSION_REVISION) p4=M4_MACRO_GET(VERSION_BUILD) p5=M4_MACRO_GET(VERSION_TYPE) INPUT)m4_dnl
