/*
palette.cpp

Таблица цветов

*/

/* Revision: 1.08 21.05.2001 $ */

/*
Modify:
  21.05.2001 SVS
    + COL_MENUDISABLEDTEXT
  06.05.2001 DJ
    ! перетрях #include
  04.12.2000 SVS
    + COL_*DIALOG*DISABLED
  06.10.2000 SVS
    - попытка ?1 исправить падение ФАРы в ночное время :-)
  13.09.2000 tran 1.04
    + COL_COMMANDLINEPREFIX
  18.07.2000 tran 1.03
    + скролбар во вьювере
  11.07.2000
    + 1 Служебная позиция перед новыми цветами :-)
  29.06.2000 SVS
    + Цветовые атрибуты для Menu ScrollBar
  25.06.2000 SVS
    ! Подготовка Master Copy
    ! Выделение в качестве самостоятельного модуля
*/

#include "headers.hpp"
#pragma hdrstop

#include "colors.hpp"

unsigned char DefaultPalette[]=
{
  F_WHITE|B_CYAN,F_WHITE|B_BLACK,F_YELLOW|B_CYAN,F_YELLOW|B_BLACK,
  F_WHITE|B_CYAN,F_WHITE|B_CYAN,

  F_BLACK|B_CYAN,F_WHITE|B_BLACK,F_YELLOW|B_CYAN,F_YELLOW|B_BLACK,

  F_LIGHTCYAN|B_BLUE,F_YELLOW|B_BLUE,F_LIGHTGRAY|B_BLUE,F_YELLOW|B_BLUE,
  F_BLACK|B_CYAN,F_YELLOW|B_CYAN,F_LIGHTCYAN|B_BLUE,F_BLACK|B_CYAN,
  F_YELLOW|B_BLUE,F_LIGHTCYAN|B_BLUE,F_YELLOW|B_CYAN,

  F_BLACK|B_LIGHTGRAY,F_YELLOW|B_LIGHTGRAY,F_BLACK|B_LIGHTGRAY,
  F_BLACK|B_LIGHTGRAY,F_YELLOW|B_LIGHTGRAY,F_BLACK|B_CYAN,
  F_BLACK|B_LIGHTGRAY,F_BLACK|B_CYAN,F_YELLOW|B_LIGHTGRAY,F_YELLOW|B_CYAN,

  F_BLACK|B_LIGHTGRAY,F_WHITE|B_BLACK,F_YELLOW|B_LIGHTGRAY,F_YELLOW|B_BLACK,

  F_WHITE|B_RED,F_YELLOW|B_RED,F_WHITE|B_RED,F_WHITE|B_RED,F_YELLOW|B_RED,
  F_BLACK|B_CYAN,F_WHITE|B_RED,F_BLACK|B_LIGHTGRAY,F_YELLOW|B_RED,
  F_YELLOW|B_LIGHTGRAY,

  F_LIGHTGRAY|B_BLACK,F_BLACK|B_CYAN,F_LIGHTGRAY|B_BLACK,

  F_LIGHTGRAY|B_BLACK,

  F_BLACK|B_CYAN,

  F_LIGHTCYAN|B_BLUE,F_BLACK|B_CYAN,F_BLACK|B_CYAN,

  F_LIGHTCYAN|B_BLUE,F_BLACK|B_CYAN,F_BLACK|B_CYAN,

  F_BLACK|B_CYAN,F_WHITE|B_CYAN,F_YELLOW|B_CYAN,F_WHITE|B_BLACK,
  F_BLACK|B_CYAN,F_BLACK|B_CYAN,

  F_YELLOW|B_CYAN,
  F_DARKGRAY|B_CYAN,
  F_LIGHTCYAN|B_BLUE,
  F_BLACK|B_CYAN,
  F_LIGHTCYAN|B_BLUE,
  F_LIGHTCYAN|B_BLACK,
  F_WHITE|B_BLACK,
  F_BLACK|B_LIGHTGRAY,
  F_YELLOW|B_BLUE,
  /* $ 11.07.2000 SVS
    + 1 Служебная позиция перед новыми цветами :-)
  */
  0,  // 1 - это есть default color
  /* SVS $ */
  /* 29.06.2000 SVS
    Цветовые атрибуты для Menu ScrollBar
  */
  F_BLACK|B_LIGHTGRAY,
  F_WHITE|B_CYAN,
  /* SVS $ */
  /* $ 18.07.2000 tran
     скролбар во вьювере */
  F_LIGHTCYAN|B_BLUE,
  /* tran 18.07.2000 $ */

  /* $ 13.09.2000 tran */
  F_LIGHTGRAY|B_BLACK,     // COL_CMDLINEPREFIX
  /* tran 13.09.2000 $ */
  /* $ 04.12.2000 SVS */
  F_DARKGRAY|B_LIGHTGRAY,  // COL_DIALOGDISABLED
  F_DARKGRAY|B_CYAN,  // COL_DIALOGEDITDISABLED
  F_DARKGRAY|B_CYAN,  // COL_DIALOGLISTDISABLED

  F_DARKGRAY|B_RED,        // COL_WARNDIALOGDISABLED
  F_DARKGRAY|B_CYAN,        // COL_WARNDIALOGEDITDISABLED
  F_DARKGRAY|B_CYAN,        // COL_WARNDIALOGLISTDISABLED
  /* SVS $ */
  F_DARKGRAY|B_CYAN,//COL_MENUDISABLEDTEXT
  0,
  0,
  0,
  0,
  0,
  0,
  0,
};


unsigned char BlackPalette[]=
{
  F_BLACK|B_LIGHTGRAY,F_LIGHTGRAY|B_BLACK,F_WHITE|B_LIGHTGRAY,F_WHITE|B_BLACK,
  F_BLACK|B_LIGHTGRAY,F_BLACK|B_LIGHTGRAY,

  F_BLACK|B_LIGHTGRAY,F_LIGHTGRAY|B_BLACK,F_WHITE|B_LIGHTGRAY,F_WHITE|B_BLACK,

  F_LIGHTGRAY|B_BLACK,F_WHITE|B_BLACK,F_LIGHTGRAY|B_BLACK,F_WHITE|B_BLACK,
  F_BLACK|B_LIGHTGRAY,F_WHITE|B_LIGHTGRAY,F_LIGHTGRAY|B_BLACK,
  F_BLACK|B_LIGHTGRAY,F_WHITE|B_BLACK,F_LIGHTGRAY|B_BLACK,
  F_BLACK|B_LIGHTGRAY,

  F_BLACK|B_LIGHTGRAY,F_WHITE|B_LIGHTGRAY,F_BLACK|B_LIGHTGRAY,
  F_BLACK|B_LIGHTGRAY,F_WHITE|B_BLACK,F_LIGHTGRAY|B_BLACK,
  F_BLACK|B_LIGHTGRAY,F_LIGHTGRAY|B_BLACK,F_WHITE|B_LIGHTGRAY,F_WHITE|B_BLACK,

  F_BLACK|B_LIGHTGRAY,F_WHITE|B_BLACK,F_WHITE|B_LIGHTGRAY,F_WHITE|B_BLACK,

  F_BLACK|B_LIGHTGRAY,F_WHITE|B_LIGHTGRAY,F_BLACK|B_LIGHTGRAY,
  F_BLACK|B_LIGHTGRAY,F_WHITE|B_BLACK,F_LIGHTGRAY|B_BLACK,F_BLACK|B_LIGHTGRAY,
  F_LIGHTGRAY|B_BLACK,F_WHITE|B_LIGHTGRAY,F_WHITE|B_BLACK,

  F_LIGHTGRAY|B_BLACK,F_BLACK|B_LIGHTGRAY,F_LIGHTGRAY|B_BLACK,

  F_LIGHTGRAY|B_BLACK,

  F_BLACK|B_LIGHTGRAY,

  F_LIGHTGRAY|B_BLACK,F_BLACK|B_LIGHTGRAY,F_BLACK|B_LIGHTGRAY,

  F_LIGHTGRAY|B_BLACK,F_BLACK|B_LIGHTGRAY,F_BLACK|B_LIGHTGRAY,

  F_LIGHTGRAY|B_BLACK,F_LIGHTGRAY|B_BLACK,F_WHITE|B_BLACK,
  F_BLACK|B_LIGHTGRAY,F_LIGHTGRAY|B_BLACK,F_LIGHTGRAY|B_BLACK,

  F_BLACK|B_LIGHTGRAY,
  F_WHITE|B_BLACK,
  F_LIGHTGRAY|B_BLACK,
  F_LIGHTGRAY|B_BLACK,
  F_LIGHTGRAY|B_BLACK,
  F_WHITE|B_BLACK,
  F_BLACK|B_LIGHTGRAY,
  F_BLACK|B_LIGHTGRAY,
  F_WHITE|B_BLACK,
  /* $ 11.07.2000 SVS
    + 1 Служебная позиция перед новыми цветами :-)
  */
  1, // 1 - это есть default mono
  /* SVS $ */
  /* 29.06.2000 SVS
    Цветовые атрибуты для Menu ScrollBar
  */
  F_BLACK|B_LIGHTGRAY,
  F_BLACK|B_LIGHTGRAY,
  /* SVS $ */
  /* $ 18.07.2000 tran
     скролбар во вьювере */
  F_LIGHTGRAY|B_BLACK,
  /* tran 18.07.2000 $ */
  /* $ 13.09.2000 tran
    COL_CMDLINEPREFIX */
  F_LIGHTGRAY|B_BLACK,
  /* tran 13.09.2000 $ */
  /* $ 04.12.2000 SVS */
  F_LIGHTGRAY|B_BLACK,      // COL_DIALOGDISABLED
  F_DARKGRAY|B_LIGHTGRAY,  // COL_DIALOGEDITDISABLED
  F_DARKGRAY|B_LIGHTGRAY,  // COL_DIALOGLISTDISABLED

  F_DARKGRAY|B_LIGHTGRAY,   // COL_WARNDIALOGDISABLED
  F_LIGHTGRAY|B_DARKGRAY,   // COL_WARNDIALOGEDITDISABLED
  F_LIGHTGRAY|B_DARKGRAY,   // COL_WARNDIALOGLISTDISABLED
  /* SVS $ */
  F_DARKGRAY|B_LIGHTGRAY,//COL_MENUDISABLEDTEXT

  0,
  0,
  0,
  0,
  0,
  0,
  0,
};

int SizeArrayPalette=sizeof(DefaultPalette)/sizeof(DefaultPalette[0]);
unsigned char Palette[sizeof(DefaultPalette)/sizeof(DefaultPalette[0])];

int FarColorToReal(int FarColor)
{
  if (FarColor<COL_FIRSTPALETTECOLOR)
    return(FarColor);
  else
    return(Palette[(FarColor-COL_FIRSTPALETTECOLOR)%SizeArrayPalette]);
}
