#define SQLITE_DEFAULT_MEMSTATUS 0
#define SQLITE_DEFAULT_WAL_SYNCHRONOUS 1

//#define SQLITE_OMIT_AUTHORIZATION 1
//#define SQLITE_OMIT_AUTOINIT 1
//#define SQLITE_OMIT_COMPILEOPTION_DIAGS 1
//#define SQLITE_OMIT_DECLTYPE 1
//#define SQLITE_OMIT_DEPRECATED 1
//#define SQLITE_OMIT_EXPLAIN 1
//#define SQLITE_OMIT_PROGRESS_CALLBACK 1

#define SQLITE_WIN32_NO_ANSI 1

#ifdef _DEBUG
#define SQLITE_DEBUG 1
#define SQLITE_ENABLE_API_ARMOR 1
#endif
