enum
{
  MOk,
  MSkip,
  MCancel,
  MCopy,
  MError,

  MFtpDiskMenu,
  MFtpMenu,

  MShiftF4,
  MShiftF7,
  MAltF6,

  MConfigTitle,
  MConfigAddToDisksMenu,
  MConfigDisksMenuDigit,
  MConfigDizNames,
  MConfigReadDiz,
  MConfigUpdateDiz,
  MConfigUploadLowCase,
  MConfigUploadDialog,
  MConfigDefPassword,
  MConfigFirewall,
  MConfigPassiveMode,

  MConnectingTo,
  MCannotConnectTo,
  MConnectionLost,
  MRestore,

  MWaitingForResponse,
  MSendingName,
  MPasswordName,
  MRequestingFolder,

  MReadingFTPFolder,
  MChangingFTPFolder,

  MFtpTitle,
  MEditFtpTitle,
  MEnterFtpTitle,
  MSaveFTPTitle,
  MFtpName,
  MUserPassword,
  MHostDescr,
  MAskLogin,
  MAsciiMode,
  MPassiveMode,
  MUseFirewall,
  MFtpSave,
  MFtpConnect,
  MFtpSelectTable,

  MFtpInfoFTPClient,
  MFtpInfoHostName,
  MFtpInfoHostDescr,
  MFtpInfoHostType,
  MFtpInfoFtpTitle,

  MRenameTitle,

  MDownloadTitle,
  MDownloadTo,
  MDownloadAscii,
  MDownload,
  MDownloadCancel,
  MCannotDownload,

  MUploadTitle,
  MUploadTo,
  MUploadAscii,
  MUpload,
  MUploadCancel,
  MCannotUpload,

  MAlreadyExist,
  MAlreadyExistRO,
  MAskOverwrite,
  MOverwrite,
  MOverwriteAll,
  MCopySkip,
  MCopySkipAll,
  MCopyResume,
  MCopyCancel,

  MStatusDownload,
  MStatusUpload,
  MStatusCPS,
  MStatusTotal,
  MStatusTime,

  MDeleteTitle,
  MDeleteFiles,
  MDeleteNumberOfFiles,
  MDeleteFolder,

  MDeleteHostsTitle,
  MDeleteHosts,
  MDeleteNumberOfHosts,
  MDeleteHostFolder,

  MDeleteDelete,
  MDeleteCancel,

  MDeleteGroupDelete,
  MDeleteGroupAll,
  MDeleteGroupCancel,

  MCannotDelete,

  MDeleting,

  MMkdirTitle,
  MMkdirName,

  MCopyHostTitle,
  MCopyHostTo,
  MMoveHostTitle,
  MMoveHostTo,

  MCannotCopyHost,
  MHostAlreadyExist,
  MHostAskOverwrite,

  MLoginInfo,
  MUserName,

  MHostColumn,
  MFileMode,

  MTableTitle,
  MTableAuto,
  MTableDefault,

  MChmodTitle,
  MCannotChmod,
  MChangingAttr,

};
