name: Extra checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  code-style-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Run checks
        working-directory: far
        run: python tools/source_validator.py


  hlf-checks:
    runs-on: windows-2019
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build and run HlfChecker
        working-directory: misc/hlf-checker
        run: dotnet run --project .\HlfChecker.csproj --configuration Release -- Verbose
